### ISSUE TITLE
boot_command option for ubuntu autoinstall

### ISSUE THREAD

**Issue by k-laughman** [nutanix-cloud-native/packer-plugin-nutanix#105]
/kind feature

Hello, are there plans to add a "boot_command" option to the plugin for Linux hosts? Currently that option exists and can be configured to allow for autoinstall confirmation with the vsphere plugin. When trying to create an ubuntu image with AHV, the interaction prompts for confirmation with autoinstall even if it is set in the cloud-config user data file. If confirmation is provided, the build runs successfully but it would be nice to have a way to pass through this confirmation for scheduled builds. 

If its possible I am missing another way to do this today, please let me know and I am happy to try it out.

**Environment:**
- packer-plugin-nutanix version (use `packer plugins installed`): packer-plugin-nutanix_v0.3.0_x5.0_windows_amd64.ex
- Packer version (use `packer version`): 1.8.4
- OS (e.g. from `/etc/os-release`): ubuntu 22.04.1

Currently, we are adding cd_files to the user-data scripts for the install and a portion of that user-data file with the autoinstall config looks like this:

#cloud-config
autoinstall:
  version: 1
  early-commands:
    - systemctl stop ssh # otherwise packer tries to connect and exceed max attempts
  locale: en_US
  keyboard:
    layout: en
    variant: us
  identity:
    hostname: xxx-ubuntu22
...

Thank you for any advice.

**Comment by tuxtof** [comment]
duplicate #49 

Hi @k-laughman 

boot_command functionality is not possible today as there is no API to have access to the console for sending keystrokes. Ubuntu-based images can only be created from existing ubuntu cloud-image and then do further customization.

As this is a limitation of AOS we cannot provide any solution yet. Please feel free to file a feature request at Nutanix Support and link to this issue.

**Comment by k-laughman** [comment]
Thank you. That was my bad - I missed this existing one in the list of issues. Appreciate the quick response and I will open a case with support to get some additional traction on the existing issue.

**Comment by tuxtof** [comment]
thanks

**Comment by tuxtof** [comment]
Hi @k-laughman

FYI we succesfully used the ubuntu installer with our Packer plugin and the autoinstall method
by using netboot in place of the iso file, by doing that you can add the correct autoinstall kernel parameters to skip confirmation

this is a good workaround waiting we are able to implement a real boot_command option
