### ISSUE TITLE
Issue uploading to Nutanix PC

### ISSUE THREAD

**Issue by ChrisReeseA** [nutanix-cloud-native/packer-plugin-nutanix#12]
When initial phase of the process where it uploads image to Prism Central, it appears to upload to all clusters and dumps the error below.  The image itself has no size and I assume it's essentially a broken image, however moving forward I'm unsure how to debug, especially if this will be pushing to all clusters in PC.  We have remote locations and this will saturate our WAN lines for the day.

*apologies for the screenshot error, couldn't grab the text to paste.

![image](https://user-images.githubusercontent.com/37385357/177420945-c66cddcd-cd0c-48df-85b5-3350f462080c.png)

![image](https://user-images.githubusercontent.com/37385357/177421110-9e23d0ce-4b97-4534-abfd-a67ae98789f1.png)

Thanks

**Comment by tuxtof** [comment]
Hello @ChrisReeseA 
Can you give more info on you config
PC & PE version ?
Architecture ?
your cleaned Packer files

**Comment by ChrisReeseA** [comment]
Folder dir
C:.
│   build_win2019.pkr.hcl
│   source_win2019.pkr.hcl
│   variables_win2019.pkr.hcl
│   vars.auto.pkrvars.hcl
│
└───init
        plugin.pkr.hcl

PC: 2021.3.0.2
PE: 5.20.0.1 (most clusters)
Running AHV on hypervisors with Nutanix hardware

[build_win2019.pkr.txt](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/files/9055278/build_win2019.pkr.txt)
[source_win2019.pkr.txt](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/files/9055279/source_win2019.pkr.txt)
[variables_win2019.pkr.hcl.txt](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/files/9055280/variables_win2019.pkr.hcl.txt)
[vars.auto.pkvars.hcl.txt](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/files/9055281/vars.auto.pkvars.hcl.txt)
[plugin.pkr.hcl.txt](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/files/9055282/plugin.pkr.hcl.txt)

**Comment by ChrisReeseA** [comment]
I updated both packer and this provider.  It seems to get a step further; now it will upload to the corresponding cluster instead of all clusters in PC.  However, I am getting this, and I think it's an issue with the name of the image??

build file
  vm_disks {
      image_type        = "ISO_IMAGE"
      source_image_name = var.windows_2019_iso_image_name
  }

  vm_disks {
      image_type        = "ISO_IMAGE"
      source_image_name = var.virtio_iso_image_name
  }

var file
windows_2019_iso_image_name     = "PC: Server 2019 Base Image"
virtio_iso_image_name           = "PC: VirtIO 1.1.6"

output
nutanix.windows2019: output will be in this color.

==> nutanix.windows2019: Creating CD disk...
    nutanix.windows2019: Warning: creating filesystem with Joliet extensions but without Rock Ridge
    nutanix.windows2019: extensions. It is highly recommended to add Rock Ridge.
    nutanix.windows2019: I: -input-charset not specified, using utf-8 (detected in locale settings)
    nutanix.windows2019: Total translation table size: 0
    nutanix.windows2019: Total rockridge attributes bytes: 0
    nutanix.windows2019: Total directory bytes: 672
    nutanix.windows2019: Path table size(bytes): 10
    nutanix.windows2019: Max brk space used 0
    nutanix.windows2019: 332 extents written (0 MB)
    nutanix.windows2019: Done copying paths from CD_dirs
==> nutanix.windows2019: Creating Packer Builder VM on Nutanix Cluster.
==> nutanix.windows2019: Error uploading temporary image:
==> nutanix.windows2019: unmarshalling error response invalid character 's' looking for beginning of value for response body stream timeout
Build 'nutanix.windows2019' finished after 5 minutes 17 seconds.


once it fails it leaves the task artifact in PC.  I'm going to see if it resolves itself and times out, but I might need to go in and kill the task manually if not:
![image](https://user-images.githubusercontent.com/37385357/180829787-4dc7cac7-abef-42e4-b093-ae95d1eae43c.png)

**Comment by tuxtof** [comment]
@ChrisReeseA can you update to v0.1.2 and 
can you give us a full trace launching the command with

PACKER_LOG=1 packer build .....

**Comment by ChrisReeseA** [comment]
root@packerdev:/home/systemadmin/.git/GL_PoSH/Packer/nutanix# PACKER_LOG=1 packer build .
2022/07/27 06:37:47 [INFO] Packer version: 1.8.2 [go1.17.11 linux amd64]
2022/07/27 06:37:47 Old default config directory found: /root/.packer.d
2022/07/27 06:37:47 [TRACE] discovering plugins in /usr/bin
2022/07/27 06:37:47 Old default config directory found: /root/.packer.d
2022/07/27 06:37:47 [TRACE] discovering plugins in /root/.packer.d/plugins
2022/07/27 06:37:47 [DEBUG] Discovered plugin: nutanix = /root/.packer.d/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64
2022/07/27 06:37:48 [INFO] found external [-packer-default-plugin-name-] builders from nutanix plugin
2022/07/27 06:37:48 [TRACE] discovering plugins in .
2022/07/27 06:37:48 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2022/07/27 06:37:48 [INFO] PACKER_CONFIG env var set; attempting to open config file: /root/.packerconfig
2022/07/27 06:37:48 [WARN] Config file doesn't exist: /root/.packerconfig
2022/07/27 06:37:48 Old default config directory found: /root/.packer.d
2022/07/27 06:37:48 [INFO] Setting cache directory: /root/.cache/packer
2022/07/27 06:37:48 Old default config directory found: /root/.packer.d
2022/07/27 06:37:48 [TRACE] validateValue: not active for virtio_iso_image_name, so skipping
2022/07/27 06:37:48 [TRACE] validateValue: not active for nutanix_insecure, so skipping
2022/07/27 06:37:48 [TRACE] validateValue: not active for nutanix_subnet, so skipping
2022/07/27 06:37:48 [TRACE] validateValue: not active for nutanix_cluster, so skipping
2022/07/27 06:37:48 [TRACE] validateValue: not active for windows_2019_iso_image_name, so skipping
2022/07/27 06:37:48 [TRACE] validateValue: not active for nutanix_username, so skipping
2022/07/27 06:37:48 [TRACE] validateValue: not active for nutanix_password, so skipping
2022/07/27 06:37:48 [TRACE] validateValue: not active for nutanix_endpoint, so skipping
2022/07/27 06:37:48 [TRACE] validateValue: not active for nutanix_port, so skipping
2022/07/27 06:37:48 [TRACE] Starting external plugin /root/.packer.d/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 start builder -packer-default-plugin-name-
2022/07/27 06:37:48 Starting plugin: /root/.packer.d/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 []string{"/root/.packer.d/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64", "start", "builder", "-packer-default-plugin-name-"}
2022/07/27 06:37:48 Waiting for RPC address for: /root/.packer.d/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 Plugin address: unix /tmp/packer-plugin3425947890
2022/07/27 06:37:48 Received unix RPC address for /root/.packer.d/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64: addr is /tmp/packer-plugin3425947890
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 Waiting for connection...
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 Serving a plugin connection...
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 [TRACE] starting builder -packer-default-plugin-name-
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 No Nutanix Port configured, defaulting to '9440'
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 No vmname assigned, setting to Packer-3MVGHNJL
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 SSHPort not set, defaulting to 22
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 SSHTimeout not set, defaulting to 20min
2022/07/27 06:37:48 [TRACE] Starting internal plugin packer-provisioner-powershell
2022/07/27 06:37:48 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-powershell"}
2022/07/27 06:37:48 Waiting for RPC address for: /usr/bin/packer
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [INFO] Packer version: 1.8.2 [go1.17.11 linux amd64]
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Old default config directory found: /root/.packer.d
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /root/.packerconfig
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [WARN] Config file doesn't exist: /root/.packerconfig
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Old default config directory found: /root/.packer.d
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [INFO] Setting cache directory: /root/.cache/packer
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Old default config directory found: /root/.packer.d
2022/07/27 06:37:48 packer-provisioner-powershell plugin: args: []string{"packer-provisioner-powershell"}
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Plugin address: unix /tmp/packer-plugin917389919
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Waiting for connection...
2022/07/27 06:37:48 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin917389919
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Serving a plugin connection...
2022/07/27 06:37:48 [TRACE] Starting internal plugin packer-provisioner-powershell
2022/07/27 06:37:48 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-powershell"}
2022/07/27 06:37:48 Waiting for RPC address for: /usr/bin/packer
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [INFO] Packer version: 1.8.2 [go1.17.11 linux amd64]
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Old default config directory found: /root/.packer.d
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /root/.packerconfig
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [WARN] Config file doesn't exist: /root/.packerconfig
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Old default config directory found: /root/.packer.d
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [INFO] Setting cache directory: /root/.cache/packer
2022/07/27 06:37:48 packer-provisioner-powershell plugin: args: []string{"packer-provisioner-powershell"}
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Old default config directory found: /root/.packer.d
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Plugin address: unix /tmp/packer-plugin4052424433
2022/07/27 06:37:48 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin4052424433
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Waiting for connection...
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Serving a plugin connection...
2022/07/27 06:37:48 [TRACE] Starting internal plugin packer-provisioner-powershell
2022/07/27 06:37:48 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-powershell"}
2022/07/27 06:37:48 Waiting for RPC address for: /usr/bin/packer
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [INFO] Packer version: 1.8.2 [go1.17.11 linux amd64]
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Old default config directory found: /root/.packer.d
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /root/.packerconfig
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [WARN] Config file doesn't exist: /root/.packerconfig
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Old default config directory found: /root/.packer.d
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [INFO] Setting cache directory: /root/.cache/packer
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Old default config directory found: /root/.packer.d
2022/07/27 06:37:48 packer-provisioner-powershell plugin: args: []string{"packer-provisioner-powershell"}
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Plugin address: unix /tmp/packer-plugin3764072529
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Waiting for connection...
2022/07/27 06:37:48 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin3764072529
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Serving a plugin connection...
2022/07/27 06:37:48 [TRACE] Starting internal plugin packer-provisioner-windows-restart
2022/07/27 06:37:48 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-windows-restart"}
2022/07/27 06:37:48 Waiting for RPC address for: /usr/bin/packer
2022/07/27 06:37:48 packer-provisioner-windows-restart plugin: [INFO] Packer version: 1.8.2 [go1.17.11 linux amd64]
2022/07/27 06:37:48 packer-provisioner-windows-restart plugin: Old default config directory found: /root/.packer.d
2022/07/27 06:37:48 packer-provisioner-windows-restart plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2022/07/27 06:37:48 packer-provisioner-windows-restart plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /root/.packerconfig
2022/07/27 06:37:48 packer-provisioner-windows-restart plugin: [WARN] Config file doesn't exist: /root/.packerconfig
2022/07/27 06:37:48 packer-provisioner-windows-restart plugin: Old default config directory found: /root/.packer.d
2022/07/27 06:37:48 packer-provisioner-windows-restart plugin: [INFO] Setting cache directory: /root/.cache/packer
2022/07/27 06:37:48 packer-provisioner-windows-restart plugin: args: []string{"packer-provisioner-windows-restart"}
2022/07/27 06:37:48 packer-provisioner-windows-restart plugin: Old default config directory found: /root/.packer.d
2022/07/27 06:37:48 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin780090892
2022/07/27 06:37:48 packer-provisioner-windows-restart plugin: Plugin address: unix /tmp/packer-plugin780090892
2022/07/27 06:37:48 packer-provisioner-windows-restart plugin: Waiting for connection...
2022/07/27 06:37:48 packer-provisioner-windows-restart plugin: Serving a plugin connection...
2022/07/27 06:37:48 [TRACE] Starting internal plugin packer-provisioner-powershell
2022/07/27 06:37:48 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-powershell"}
2022/07/27 06:37:48 Waiting for RPC address for: /usr/bin/packer
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [INFO] Packer version: 1.8.2 [go1.17.11 linux amd64]
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Old default config directory found: /root/.packer.d
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /root/.packerconfig
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [WARN] Config file doesn't exist: /root/.packerconfig
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Old default config directory found: /root/.packer.d
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [INFO] Setting cache directory: /root/.cache/packer
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Old default config directory found: /root/.packer.d
2022/07/27 06:37:48 packer-provisioner-powershell plugin: args: []string{"packer-provisioner-powershell"}
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Plugin address: unix /tmp/packer-plugin2157642280
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Waiting for connection...
2022/07/27 06:37:48 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin2157642280
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Serving a plugin connection...
2022/07/27 06:37:48 [TRACE] Starting internal plugin packer-provisioner-powershell
2022/07/27 06:37:48 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-powershell"}
2022/07/27 06:37:48 Waiting for RPC address for: /usr/bin/packer
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [INFO] Packer version: 1.8.2 [go1.17.11 linux amd64]
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Old default config directory found: /root/.packer.d
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /root/.packerconfig
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [WARN] Config file doesn't exist: /root/.packerconfig
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Old default config directory found: /root/.packer.d
2022/07/27 06:37:48 packer-provisioner-powershell plugin: [INFO] Setting cache directory: /root/.cache/packer
2022/07/27 06:37:48 packer-provisioner-powershell plugin: args: []string{"packer-provisioner-powershell"}
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Old default config directory found: /root/.packer.d
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Plugin address: unix /tmp/packer-plugin1996692737
2022/07/27 06:37:48 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin1996692737
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Waiting for connection...
2022/07/27 06:37:48 packer-provisioner-powershell plugin: Serving a plugin connection...
2022/07/27 06:37:48 Build debug mode: false
2022/07/27 06:37:48 Force build: false
2022/07/27 06:37:48 On error:
2022/07/27 06:37:48 Waiting on builds to complete...
2022/07/27 06:37:48 Starting build run: nutanix.windows2019
2022/07/27 06:37:48 Running builder:
2022/07/27 06:37:48 [INFO] (telemetry) Starting builder nutanix.windows2019
nutanix.windows2019: output will be in this color.

2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 PC Host from config: 10.0.4.189
==> nutanix.windows2019: Creating CD disk...
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 CD path: /tmp/packer1372040333.iso
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 Wrote 12111 bytes to /tmp/packer_to_cdrom2660018798/netkvm.cat
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 Wrote 14718 bytes to /tmp/packer_to_cdrom2660018798/netkvm.inf
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 Wrote 155992 bytes to /tmp/packer_to_cdrom2660018798/netkvm.sys
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 Wrote 12120 bytes to /tmp/packer_to_cdrom2660018798/vioscsi.cat
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 Wrote 3008 bytes to /tmp/packer_to_cdrom2660018798/vioscsi.inf
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 Wrote 77136 bytes to /tmp/packer_to_cdrom2660018798/vioscsi.sys
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 Wrote 12722 bytes to Autounattend.xml
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 Wrote 2595 bytes to configwinrm.ps1
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 Wrote 1090 bytes to cert.pem
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 Wrote 1625 bytes to config.ps1
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 Wrote 2880 bytes to win-update.ps1
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 Wrote 1119 bytes to skipOOBE.xml
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 Wrote 1319 bytes to Cleanup.ps1
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 Executing: /usr/bin/mkisofs [-joliet -volid packer -o /tmp/packer1372040333.iso /tmp/packer_to_cdrom2660018798]
    nutanix.windows2019: Warning: creating filesystem with Joliet extensions but without Rock Ridge
    nutanix.windows2019: extensions. It is highly recommended to add Rock Ridge.
    nutanix.windows2019: I: -input-charset not specified, using utf-8 (detected in locale settings)
    nutanix.windows2019: Total translation table size: 0
    nutanix.windows2019: Total rockridge attributes bytes: 0
    nutanix.windows2019: Total directory bytes: 672
    nutanix.windows2019: Path table size(bytes): 10
    nutanix.windows2019: Max brk space used 0
    nutanix.windows2019: 332 extents written (0 MB)
    nutanix.windows2019: Done copying paths from CD_dirs
==> nutanix.windows2019: Creating Packer Builder VM on Nutanix Cluster.
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 Check for temporary iso-disks to attach
2022/07/27 06:37:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:48 temporary iso found, /tmp/packer1372040333.iso
2022/07/27 06:37:50 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:50 Creating Image: RUNNING
2022/07/27 06:37:55 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:37:55 Creating Image: COMPLETE
2022/07/27 06:42:55 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:42:55 Error while upload, unmarshalling error response invalid character 's' looking for beginning of value for response body stream timeout
==> nutanix.windows2019: Error uploading temporary image:
==> nutanix.windows2019: unmarshalling error response invalid character 's' looking for beginning of value for response body stream timeout
2022/07/27 06:42:55 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/27 06:42:55 Deleting CD disk: /tmp/packer1372040333.iso
2022/07/27 06:42:55 [INFO] (telemetry) ending nutanix.windows2019
==> Wait completed after 5 minutes 7 seconds
==> Builds finished but no artifacts were created.
Build 'nutanix.windows2019' finished after 5 minutes 7 seconds.
2022/07/27 06:42:55 [INFO] (telemetry) Finalizing.

==> Wait completed after 5 minutes 7 seconds

==> Builds finished but no artifacts were created.
2022/07/27 06:42:57 [WARN] (telemetry) Error finalizing report. This is safe to ignore. Post "https://checkpoint-api.hashicorp.com/v1/telemetry/packer": context deadline exceeded
2022/07/27 06:42:57 waiting for all plugin processes to complete...
2022/07/27 06:42:57 /usr/bin/packer: plugin process exited
2022/07/27 06:42:57 /usr/bin/packer: plugin process exited
2022/07/27 06:42:57 /usr/bin/packer: plugin process exited
2022/07/27 06:42:57 /usr/bin/packer: plugin process exited
2022/07/27 06:42:57 /usr/bin/packer: plugin process exited
2022/07/27 06:42:57 /usr/bin/packer: plugin process exited
2022/07/27 06:42:57 /root/.packer.d/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64: plugin process exited

**Comment by ChrisReeseA** [comment]
Ran same build with a different PE in PC, it seems to get past the image upload.  This was a network issue it looks like so you can disregard the above and close this issue.  Thank you for your help!!

-Chris

**Comment by tuxtof** [comment]
thanks for the feedback @ChrisReeseA
