### ISSUE TITLE
Add GPU support

### ISSUE THREAD

**Issue by tuxtof** [nutanix-cloud-native/packer-plugin-nutanix#123]
/kind feature

**Describe the solution you'd like**

allow to assign GPU to the temporary VM to be able to install correctly Nvidia drivers

for both GPU and vGPU

**Comment by Torqu3Wr3nch** [comment]
+1

**Comment by Torqu3Wr3nch** [comment]
You can assign this development request to me.

**Comment by Torqu3Wr3nch** [comment]
Prototype dev completed and working. Expect a PR shortly.
