### ISSUE TITLE
Allow force download existing image

### ISSUE THREAD

**Issue by tuxtof** [nutanix-cloud-native/packer-plugin-nutanix#124]
/kind feature

**Describe the solution you'd like**

if an image already exist with the same DL url , it will be used
we need to propose an option to force download a new image everytime

**Comment by ktinthecloud** [comment]
I'm using **source_image_uri** to download from "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img".  When a new build kicks off it already has the image downloaded locally so it doesn't pull a new one down from ubuntu.com.  Can we use **image_delete = true** or something similar to delete the source image after Packer has built the packer image?
