### ISSUE TITLE
packer build crash when no ssh connection available

### ISSUE THREAD

**Issue by mjtrangoni** [nutanix-cloud-native/packer-plugin-nutanix#130]
/kind bug

**What steps did you take and what happened:**

I am new to packer, and wanted to test it out. 
My Nutanix cluster is not directly accessible from my local network, so I am only SSH-tunneling the PRISM interface on port 9440. 
From the Ubuntu example, I removed the provisioner and the ssh configuration, so that no direct connection would be theoretically needed (correct me if I am wrong).

See,
```shell
--- a/example/build.nutanix.pkr.hcl
+++ b/example/build.nutanix.pkr.hcl
@@ -16,7 +16,7 @@ build {
   }

   provisioner "shell" {
-    only = ["nutanix.centos", "nutanix.centos-kickstart" ,"nutanix.ubuntu"]
+    only = ["nutanix.centos", "nutanix.centos-kickstart"]
     environment_vars = [
       "FOO=hello world",
     ]

--- a/example/source.nutanix.pkr.hcl
+++ b/example/source.nutanix.pkr.hcl
   shutdown_command  = "echo 'packer' | sudo -S shutdown -P now"
   shutdown_timeout = "2m"
-  ssh_password     = "packer"
-  ssh_username     = "builder"
+  ssh_password     = ""
+  ssh_username     = ""
 }
``` 

Running `PACKER_LOG=1 packer build -debug -force -only nutanix.ubuntu .` it crashed.

**What did you expect to happen:**

I would expect the plugin to handle this case and generate an image without any provisioner step.

**Anything else you would like to add:**

[crash.log](https://gist.github.com/mjtrangoni/8c7ad57f143084782f928ba7c60bd227)

**Environment:**

- packer-plugin-nutanix version (use `packer plugins installed`): 
```shell
$ packer plugins installed
/Users/mtrangoni/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.7.1_x5.0_darwin_arm64
```
- Packer version (use `packer version`): 
```Packer v1.9.1```
- OS (e.g. from `/etc/os-release`): 
```shell
$ sw_vers
ProductName:            macOS
ProductVersion:         13.4.1
BuildVersion:           22F82
```

**Comment by tuxtof** [comment]
ssh is mandatory, used to poweroff properly the VM

**Comment by tuxtof** [comment]
Hi @mjtrangoni 
If you set your communicator to none
It will normally solve your issue
