### ISSUE TITLE
How to delete the iso from cd_files

### ISSUE THREAD

**Issue by darthVikes** [nutanix-cloud-native/packer-plugin-nutanix#143]
Looks like there is an ISO that gets dynmically created and uploaded to images when you are using "cd_files", how do I delete this ISO after packer is completed?

Also, Is ther a cd_name attribute that I can also name it the same each time?   if so, is there a cd_overwriet option? so if its there it will just delete and create a new one? 

Otherwise I have a ton of Packer_* iso files that are gathering on each deployment?

**Comment by tuxtof** [comment]
today, image is automatically deleted if the build is succesfull
i will change the behaviour to change it and delete it in all case

**Comment by darthVikes** [comment]
Perfect, as it really doesn't need to there after the deploy is done that I can think of anyway.
