### ISSUE TITLE
Add more description into attributes for nutanix

### ISSUE THREAD

**Issue by darthVikes** [nutanix-cloud-native/packer-plugin-nutanix#145]
I was able to get some informtion here; 
https://github.com/nutanix-cloud-native/packer-plugin-nutanix/blob/main/docs/builders/nutanix.mdx

but its not real clear on what each does and can be used fo so it would be good to include a longer explanation of what each attribute is and what it can be used for with an example?

**Comment by tuxtof** [comment]
the renderer documentation is available here
https://developer.hashicorp.com/packer/plugins/builders/nutanix
https://developer.hashicorp.com/packer/plugins/builders/nutanix/nutanix

of course there is always room to improvement

what points in particular do you feel need to be improved? 

thanks for your help

**Comment by darthVikes** [comment]
So maybe its a bit more of the variables too that are confusing me.    

like nutanix_ *     All attributes that are used to log in to prisim.    OK perfect.


cluster_name ?      as in nutanix_cluster_name ?   but then description says its the nutanix cluster name. 

os_type?  so assuming this some kind of vm, had to go back up to very top to see that this section was about the temporary vm to create the  image?      maybe should be vm_os_type ?   to keep it w/ similar variable names as other corresponding variables?

nutanix_port :     would good to put in the default port number ? 

vm_name :    Nice to see this added now for the vm_name for the temporary vm

cpu?    :       aka the vm_cpu ?   for temporary vm ?
memory_mb :     vm_memory_mb ?


cd_files;    these then have a different variable name that obviouslly different from the vm attribute names for the temporary VM  but would be good to add an example here on how to use.

cd_label:    somewhere I believe in the examples folder where OEMDRV was used?   assuming I should be using that label so that it can find any files it may need?   aka kickstarter file ?   Or doesn't this label matter?   Or does it default to OEMDRV?  

ip_wait_timeout :   good

vm_categories:    example?

project;   might be good enough, 



image-name:  ?  still confusion here on what these are?  vs vm_name    ... doesn't seem to be the temporary iso created and uploaded to images as that's created dynamicaly with cd_files, cd_label

image_description?   above
image_categories?  above

force-deregister?   does that go with the output image_* or vm_*     seems to delete the vm_name type vm that i'm working on creating when if fails. 

image_delete?  seems more like thse parameters are for what is put into the images area in nutanix?  where as the vm_* gets put into the vm area ;   aka back to other request to delete these images after packer is run?  maybe that's why they stuck around.    aka ; https://github.com/nutanix-cloud-native/packer-plugin-nutanix/issues/143 ?

image_export?   nots ure what this does, something about exporting a folder to images?   example?


shutdown_command ?  aka   vm_shutdown_command?   better to group this variable with the other vm variables?
shutdown_timeout?  aka vm_shutdown_timeout?   better to group this variable with the other vm variables?
communicator: aka vm_protocol?   decription is helpful for kinda help determine how its trying to connect

user_data ? aka vm_cloudinit ?  example?
ssh username ?  aka vm_ssh_username?
ssh password ? aka vm_ssh_password ? 

winrm* all assocated to communicator or vm_protocol?  so could be under that?   vm_protocol_ssh_username, vm_protocol_ssh_password, vm_protocol_winrm_port, vm_protocol_winrm_insecure ? etc?


image_type ?  what 3 parameters?   example?

source_image_name?  is this like the iso image we are using to load windows?   iso_image_name ?     aka like windows / linux?  packer for vmware also was able to download that from a repo and upload it to a vmware datastore?  could this do the same vs having to manually upload the iso dvd of windows / linux to the image repository?

source_image_uuid ? example?
source_image_uri? Example?
source_image_delete? example?
source_image_force?  example?

disk_size_gb?   good example/sample that is included.  that helps.

subnet_name?       good example, helped to undertand this needed to be connected to our network uplink names
subnet_uuid;     ;    could even be vm_subnet_name, and vm_subnet_uuid?


ah, now seeeing an example more of catorries configuation that I was thinking may have been better ot have more up with the other variables?



Not trying to spark an entire remap of things but better descriptions of what they are and how to use them would certaily be a helpful addition.

Thanks!

**Comment by darthVikes** [comment]
This is probably too much, big rock.  will close and do more specific requests if needed for documentation.
