### ISSUE TITLE
Script Execute issue?

### ISSUE THREAD

**Issue by darthVikes** [nutanix-cloud-native/packer-plugin-nutanix#146]
`

    "provisioners": [
      {
        "type": "file",
        "source": "{{user `vm_cleanup_source`}}",
        "destination": "{{user `vm_cleanup_destination`}}"
      },
      {
        "type": "shell",
        "inline": ["chmod +x {{user `vm_cleanup_destination`}}"]
      },
      {
        "type": "shell",
        "inline": ["sh {{user `vm_cleanup_destination`}}"]
      },
      {
        "type": "file",
        "source": "{{user `cloud_config_source`}}",
        "destination": "{{user `cloud_config_destination`}}"
      }
    ]

`

==> nutanix: Using SSH communicator to connect: 10.223.101.133
==> nutanix: Waiting for SSH to become available...
==> nutanix: Connected to SSH!
==> nutanix: Uploading ./scripts/clean4vmtemplate.sh => /root/scripts/clean4vmtemplate.sh
    nutanix: clean4vmtemplate.sh 5.98 KiB / 5.98 KiB [=======================================================================================================================================================================================] 100.00% 0s
==> nutanix: Provisioning with shell script: /tmp/packer-shell513573702
==> nutanix: chmod: cannot access '/root/scripts/clean4vmtemplate.sh': Not a directory
==> nutanix: Provisioning step had errors: Running the cleanup provisioner, if present...
==> nutanix: Force deleting virtual machine...
    nutanix: CD disk successfully deleted
    nutanix: Virtual machine successfully deleted
Build 'nutanix' errored after 12 minutes 50 seconds: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

**Comment by darthVikes** [comment]
Added the chmod shell command but didn't seem to help  much, normally when using packer w/ vmware I didnt need to do that step anyway.  However, there seems to be some issue here with the file maybe not being there to execute? even though it seems to have copied the file?

**Comment by tuxtof** [comment]
provisioners are not specific to Nutanix plugin but generic to packer
there behaviour is the same what is the infra plugin you are using

can you share your entire project file, so we can have a global view

and for info you can simplify the three first provisioning step with something like that

```
{
      "type": "shell",
      "script": "{{user `vm_cleanup_source`}}"
},
```

**Comment by darthVikes** [comment]
Right, and this normally works perfectly with privisioning with vmware.   still doing some troubleshooting,  guessing its something that i'm probably doing different.  as I wouldn't suspect this to be really a nutanix plugin issue.  I'll just close this one as I dont think its anything specifically with nutanix.
