### ISSUE TITLE
Cluster not found error

### ISSUE THREAD

**Issue by ktinthecloud** [nutanix-cloud-native/packer-plugin-nutanix#15]
I'm getting a cluster not found error even though the name of the cluster is correct.

`~/projects/ecco-se-packer-nutanix/example$ packer build -debug -only nutanix.windows . 
Debug mode enabled. Builds will not be parallelized.
nutanix.windows: output will be in this color.

==> nutanix.windows: Creating CD disk...
    nutanix.windows: xorriso 1.5.2 : RockRidge filesystem manipulator, libburnia project.
    nutanix.windows: Drive current: -outdev 'stdio:/tmp/packer3117321950.iso'
    nutanix.windows: Media current: stdio file, overwriteable
    nutanix.windows: Media status : is blank
    nutanix.windows: Media summary: 0 sessions, 0 data blocks, 0 data, 10.7g free
    nutanix.windows: xorriso : WARNING : -volid text does not comply to ISO 9660 / ECMA 119 rules
    nutanix.windows: Added to ISO image: directory '/'='/tmp/packer_to_cdrom293672890'
    nutanix.windows: xorriso : UPDATE :       2 files added in 1 seconds
    nutanix.windows: xorriso : UPDATE :       2 files added in 1 seconds
    nutanix.windows: ISO image produced: 192 sectors
    nutanix.windows: Written to medium : 192 sectors at LBA 0
    nutanix.windows: Writing to 'stdio:/tmp/packer3117321950.iso' completed successfully.
    nutanix.windows: Done copying paths from CD_dirs
==> nutanix.windows: Creating Packer Builder VM on Nutanix Cluster.
==> nutanix.windows: Error uploading temporary image:
==> nutanix.windows: **cluster not found NTNXCLUS01**
Build 'nutanix.windows' finished after 125 milliseconds 826 microseconds.`

**Comment by wolfganghuse** [comment]
Hello @ktinthecloud 
Please also check if `nutanix_insecure    = false` is set correctly in case you don´t have valid SSL Cert on your PrismCentral... T

**Comment by ktinthecloud** [comment]
user@host:~/projects/ecco-se-packer-nutanix/example$ **PACKER_LOG=1 packer build -debug -only nutanix.windows .**
2022/07/25 09:07:18 [INFO] Packer version: 1.8.2 [go1.17.11 linux amd64]
2022/07/25 09:07:18 [TRACE] discovering plugins in /usr/bin
2022/07/25 09:07:18 [TRACE] discovering plugins in /home/user@host.com/.config/packer/plugins
2022/07/25 09:07:18 [DEBUG] Discovered plugin: nutanix = /home/user@host.com/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64
2022/07/25 09:07:18 [INFO] found external [-packer-default-plugin-name-] builders from nutanix plugin
2022/07/25 09:07:18 [TRACE] discovering plugins in .
2022/07/25 09:07:18 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2022/07/25 09:07:18 [INFO] PACKER_CONFIG env var set; attempting to open config file: /home/user@host.com/.packerconfig
2022/07/25 09:07:18 [WARN] Config file doesn't exist: /home/user@host.com/.packerconfig
2022/07/25 09:07:18 [INFO] Setting cache directory: /home/user@host.com/.cache/packer
2022/07/25 09:07:18 [TRACE] listing potential installations for "github.com/nutanix-cloud-native/nutanix" that match ">= 0.1.0". plugingetter.ListInstallationsOptions{FromFolders:[]string{"/usr/bin/packer", ".", "/home/user@host.com/.config/packer/plugins"}, BinaryInstallationOptions:plugingetter.BinaryInstallationOptions{APIVersionMajor:"5", APIVersionMinor:"0", OS:"linux", ARCH:"amd64", Ext:"", Checksummers:[]plugingetter.Checksummer{plugingetter.Checksummer{Type:"sha256", Hash:(*sha256.digest)(0xc00015e100)}}}}
2022/07/25 09:07:18 [TRACE] Found the following "github.com/nutanix-cloud-native/nutanix" installations: [{/home/user@host.com/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 v0.1.1}]
2022/07/25 09:07:18 [INFO] found external [-packer-default-plugin-name-] builders from nutanix plugin
2022/07/25 09:07:18 [TRACE] validateValue: not active for nutanix_username, so skipping
2022/07/25 09:07:18 [TRACE] validateValue: not active for nutanix_insecure, so skipping
2022/07/25 09:07:18 [TRACE] validateValue: not active for centos_iso_image_name, so skipping
2022/07/25 09:07:18 [TRACE] validateValue: not active for nutanix_subnet, so skipping
2022/07/25 09:07:18 [TRACE] validateValue: not active for nutanix_cluster, so skipping
2022/07/25 09:07:18 [TRACE] validateValue: not active for centos_disk_image_name, so skipping
2022/07/25 09:07:18 [TRACE] validateValue: not active for windows_2016_iso_image_name, so skipping
2022/07/25 09:07:18 [TRACE] validateValue: not active for virtio_iso_image_name, so skipping
2022/07/25 09:07:18 [TRACE] validateValue: not active for nutanix_password, so skipping
2022/07/25 09:07:18 [TRACE] validateValue: not active for nutanix_endpoint, so skipping
2022/07/25 09:07:18 [TRACE] validateValue: not active for nutanix_port, so skipping
2022/07/25 09:07:18 [TRACE] Starting external plugin /home/user@host.com/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 start builder -packer-default-plugin-name-
2022/07/25 09:07:18 Starting plugin: /home/user@host.com/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 []string{"/home/user@host.com/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64", "start", "builder", "-packer-default-plugin-name-"}
2022/07/25 09:07:18 Waiting for RPC address for: /home/user@host.com/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64
2022/07/25 09:07:18 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/25 09:07:18 Plugin address: unix /tmp/packer-plugin3178103366
2022/07/25 09:07:18 Received unix RPC address for /home/user@host.com/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64: addr is /tmp/packer-plugin3178103366
2022/07/25 09:07:18 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/25 09:07:18 Waiting for connection...
2022/07/25 09:07:18 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/25 09:07:18 Serving a plugin connection...
2022/07/25 09:07:18 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/25 09:07:18 [TRACE] starting builder -packer-default-plugin-name-
2022/07/25 09:07:18 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/25 09:07:18 No Nutanix Port configured, defaulting to '9440'
2022/07/25 09:07:18 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/25 09:07:18 No vmname assigned, setting to Packer-09V9RN2X
2022/07/25 09:07:18 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/25 09:07:18 SSHPort not set, defaulting to 22
2022/07/25 09:07:18 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/25 09:07:18 SSHTimeout not set, defaulting to 20min
2022/07/25 09:07:18 [TRACE] Starting internal plugin packer-provisioner-powershell
2022/07/25 09:07:18 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-powershell"}
2022/07/25 09:07:18 Waiting for RPC address for: /usr/bin/packer
2022/07/25 09:07:19 packer-provisioner-powershell plugin: [INFO] Packer version: 1.8.2 [go1.17.11 linux amd64]
2022/07/25 09:07:19 packer-provisioner-powershell plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2022/07/25 09:07:19 packer-provisioner-powershell plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /home/user@host.com/.packerconfig
2022/07/25 09:07:19 packer-provisioner-powershell plugin: [WARN] Config file doesn't exist: /home/user@host.com/.packerconfig
2022/07/25 09:07:19 packer-provisioner-powershell plugin: [INFO] Setting cache directory: /home/user@host.com/.cache/packer
2022/07/25 09:07:19 packer-provisioner-powershell plugin: args: []string{"packer-provisioner-powershell"}
2022/07/25 09:07:19 packer-provisioner-powershell plugin: Plugin address: unix /tmp/packer-plugin2954467408
2022/07/25 09:07:19 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin2954467408
2022/07/25 09:07:19 packer-provisioner-powershell plugin: Waiting for connection...
2022/07/25 09:07:19 packer-provisioner-powershell plugin: Serving a plugin connection...
2022/07/25 09:07:19 [TRACE] Starting internal plugin packer-provisioner-windows-restart
2022/07/25 09:07:19 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-windows-restart"}
2022/07/25 09:07:19 Waiting for RPC address for: /usr/bin/packer
2022/07/25 09:07:19 packer-provisioner-windows-restart plugin: [INFO] Packer version: 1.8.2 [go1.17.11 linux amd64]
2022/07/25 09:07:19 packer-provisioner-windows-restart plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2022/07/25 09:07:19 packer-provisioner-windows-restart plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /home/user@host.com/.packerconfig
2022/07/25 09:07:19 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin1893316654
2022/07/25 09:07:19 packer-provisioner-windows-restart plugin: [WARN] Config file doesn't exist: /home/user@host.com/.packerconfig
2022/07/25 09:07:19 packer-provisioner-windows-restart plugin: [INFO] Setting cache directory: /home/user@host.com/.cache/packer
2022/07/25 09:07:19 packer-provisioner-windows-restart plugin: args: []string{"packer-provisioner-windows-restart"}
2022/07/25 09:07:19 packer-provisioner-windows-restart plugin: Plugin address: unix /tmp/packer-plugin1893316654
2022/07/25 09:07:19 packer-provisioner-windows-restart plugin: Waiting for connection...
2022/07/25 09:07:19 packer-provisioner-windows-restart plugin: Serving a plugin connection...
Debug mode enabled. Builds will not be parallelized.
2022/07/25 09:07:19 Build debug mode: true
2022/07/25 09:07:19 Force build: false
nutanix.windows: output will be in this color.

2022/07/25 09:07:19 On error: 
2022/07/25 09:07:19 Debug enabled, so waiting for build to finish: nutanix.windows
2022/07/25 09:07:19 Starting build run: nutanix.windows
2022/07/25 09:07:19 Running builder: 
2022/07/25 09:07:19 [INFO] (telemetry) Starting builder nutanix.windows
2022/07/25 09:07:19 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/25 09:07:19 PC Host from config: ntnxprismc.tandemdiabetes.com
==> nutanix.windows: Creating CD disk...
2022/07/25 09:07:19 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/25 09:07:19 CD path: /tmp/packer3094018441.iso
2022/07/25 09:07:19 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/25 09:07:19 Wrote 14139 bytes to autounattend.xml
2022/07/25 09:07:19 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/25 09:07:19 Wrote 3697 bytes to win-update.ps1
2022/07/25 09:07:19 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/25 09:07:19 Executing: /usr/bin/xorriso [-as genisoimage -rock -joliet -volid packer -output /tmp/packer3094018441.iso /tmp/packer_to_cdrom794159448]
    nutanix.windows: xorriso 1.5.2 : RockRidge filesystem manipulator, libburnia project.
    nutanix.windows: Drive current: -outdev 'stdio:/tmp/packer3094018441.iso'
    nutanix.windows: Media current: stdio file, overwriteable
    nutanix.windows: Media status : is blank
    nutanix.windows: Media summary: 0 sessions, 0 data blocks, 0 data, 10.7g free
    nutanix.windows: xorriso : WARNING : -volid text does not comply to ISO 9660 / ECMA 119 rules
    nutanix.windows: Added to ISO image: directory '/'='/tmp/packer_to_cdrom794159448'
    nutanix.windows: xorriso : UPDATE :       2 files added in 1 seconds
    nutanix.windows: xorriso : UPDATE :       2 files added in 1 seconds
    nutanix.windows: ISO image produced: 192 sectors
    nutanix.windows: Written to medium : 192 sectors at LBA 0
    nutanix.windows: Writing to 'stdio:/tmp/packer3094018441.iso' completed successfully.
    nutanix.windows: Done copying paths from CD_dirs
==> nutanix.windows: Creating Packer Builder VM on Nutanix Cluster.
2022/07/25 09:07:19 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/25 09:07:19 Check for temporary iso-disks to attach
2022/07/25 09:07:19 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/25 09:07:19 temporary iso found, /tmp/packer3094018441.iso
==> nutanix.windows: Error uploading temporary image:
==> nutanix.windows: cluster not found NTNXCLUS01
2022/07/25 09:07:19 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/25 09:07:19 Deleting CD disk: /tmp/packer3094018441.iso
Build 'nutanix.windows' finished after 124 milliseconds 630 microseconds.

2022/07/25 09:07:19 [INFO] (telemetry) ending nutanix.windows
2022/07/25 09:07:19 Waiting on builds to complete...
==> Wait completed after 124 milliseconds 672 microseconds

==> Builds finished but no artifacts were created.
==> Wait completed after 124 milliseconds 672 microseconds
==> Builds finished but no artifacts were created.
2022/07/25 09:07:19 [INFO] (telemetry) Finalizing.
2022/07/25 09:07:19 waiting for all plugin processes to complete...
2022/07/25 09:07:19 /usr/bin/packer: plugin process exited
2022/07/25 09:07:19 /usr/bin/packer: plugin process exited
2022/07/25 09:07:19 /home/user@host.com/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64: plugin process exited

**Comment by ktinthecloud** [comment]
admin@NTNX-000-00-0-00-A-PCVM:~$ nuclei cluster.list
2022/07/25 16:05:05 Connected to 000.00.00.00:9876
2022/07/25 16:05:05 Authenticating connection 0x0
2022/07/25 16:05:05 nuclei is attempting to connect to Zookeeper
2022/07/25 16:05:05 Authenticated: id=0x00000000000000, timeout=20000
"Total Entities : 2"
"Entities :"
Name        UUID                                  State
NTNXCLUS01  xxxxxxxxxx-xxxx-xxxx-xxxx-7cc255071d24  COMPLETE
Unnamed     xxxxxxxx-xxxx-xxxx-xxxx-81cb7a9f636c  COMPLETE

**Comment by ktinthecloud** [comment]
variable "nutanix_insecure" {
  type = bool
  default = false
}

**Comment by wolfganghuse** [comment]
Ok, we will have a new 0.12 Release soon with better error handling/output.

**Comment by wolfganghuse** [comment]
@ktinthecloud just an additional question: Did you change the `nutanix_insecure ` in the variable section like you pasted above ? This is only the default value when no setting is done elsewhere. 
Within the Example the value is also set:
[https://github.com/nutanix-cloud-native/packer-plugin-nutanix/blob/main/example/settings.auto.pkrvars.hcl](url)
`nutanix_insecure    = false `
You need to change it there to `true` if you are using untrusted certs.

**Comment by wolfganghuse** [comment]
@ktinthecloud the new release is now available

**Comment by ktinthecloud** [comment]
@wolfganghuse that was it.  Thanks for your help!
