### ISSUE TITLE
Disk Configuration

### ISSUE THREAD

**Issue by darthVikes** [nutanix-cloud-native/packer-plugin-nutanix#152]
I have disks configured like this;  

            "vm_disks": [
              {
                "image_type"        : "ISO_IMAGE",                   
                "source_image_name" : "{{user `linux_iso_image_name`}}",
                "source_image_delete" : "true"
              },
              {
                "image_type"        : "DISK",                   
                "disk_size_gb"      : "1"
              },
              {
                "image_type"        : "DISK",                   
                "disk_size_gb"      : "50"
              },
              {
                "image_type"        : "DISK",                   
                "disk_size_gb"      : "5"
              },
              {
                "image_type"        : "DISK",                   
                "disk_size_gb"      : "2"
              }                                          
            ],

Problem is i'am seeing inconsistant results where I hit this error.  if I re-run it, it will eventually work correctly w/o changing anything.

![image](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/assets/12534245/5a7fcdf0-77b8-434b-bd4f-38089c07da35)

its imporant that the right disk gets put in teh right spot, and there doesn't seem to be a way to indicate that via scsi ids? aka ability to specify scsi id 0:1, 0:2, 0:3, 0:4 in the packer code.  however, it does look like its in teh correct order via prisim at least on order I put it above.   However, then why the error?   Doing same in vmwre works fine, but I am able to put in the scsi_ids with vmware.

![image](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/assets/12534245/27d022d3-852f-468a-9d05-313fd22752e1)

**Comment by tuxtof** [comment]
valid point, let me add it in the todo list

**Comment by tuxtof** [comment]
just try to reproduce without success but small difference i'm using HCL to define packer config
can you share me you json based build file to try to reproduce

**Comment by darthVikes** [comment]
have 2 files, will upload here. 
[template.json.txt](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/files/12443541/template.json.txt)
[environment.json.txt](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/files/12443542/environment.json.txt)

**Comment by tuxtof** [comment]
Hello @darthVikes 

even with json file i'm not able to reproduce your issue for now, on my side disk are always correctly ordered
can you share me your ks.cfg file please

**Comment by darthVikes** [comment]
[ks.cfg.txt](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/files/12488539/ks.cfg.txt)

**Comment by darthVikes** [comment]
Strange, maybe the ks.cfg file will help.   If the disks are being ordered properly, then you would think it would have enough space to do the next step for the installation and formatting. but that's where it seems to get stuck and it generally was every other time for me that it was happening that this not enough space error would come up.

**Comment by tuxtof** [comment]
thanks for the files, i will try to reproduce after my PTO, stay tuned

**Comment by tuxtof** [comment]
Hello @darthVikes 

i have try your ks file but it don't work for me

![image](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/assets/180613/dab1d8d0-39b5-4bcf-a13e-53f7146d66c5)

i have modifed the ks file a little bit and seems ok for me

i configure disks part like that
```
part /boot --fstype="xfs" --ondisk=sda --grow
part pv.1 --fstype="lvmpv" --ondisk=sdb --grow
part pv.2 --fstype="lvmpv" --ondisk=sdc --grow
part pv.3 --fstype="lvmpv" --ondisk=sdd --grow

volgroup vg_root pv.1
volgroup vg_swap pv.2
volgroup vg_data pv.3

logvol /        --fstype="xfs" --size=4096 --name=lv_root   --vgname=vg_root
logvol /home    --fstype="xfs" --size=2048 --name=lv_home   --vgname=vg_root
logvol /tmp     --fstype="xfs" --size=2048 --name=lv_tmp    --vgname=vg_root
logvol /usr     --fstype="xfs" --size=4096 --name=lv_usr    --vgname=vg_root
logvol /var     --fstype="xfs" --size=4096 --name=lv_var    --vgname=vg_root
logvol /var/log --fstype="xfs" --size=2048 --name=lv_varlog --vgname=vg_root
logvol /opt     --fstype="xfs" --size=2048 --name=lv_opt    --vgname=vg_root
logvol swap                    --size=2048 --name=lv_swap   --vgname=vg_swap
logvol /data    --fstype="xfs" --size=1024 --name=lv_data   --vgname=vg_data
```

amd remove you `%pre` part

i don't hit any disks order issue

**Comment by darthVikes** [comment]
You should need to modify anything in the Kickstarter, as that is all intended.  Did you try that several times?    

It seems if I retry it, it will eventually work as it eventually will put it on the right disk and so it fits, you don't get the errors with not having enough space, and then the VG does get created and doesn't complain about not having enough space.     So I think in those cases it is finding the correct disk, aka sdb or disk.1 vs other disks?

I think based on what you said you are also seeing the problem where it's not hitting the right disk.    Also, why I think it's important to be able specify the SCSI ids and what controller # you put them on so with packer/Nutanix you can't seem to do that which I think is also a huge problem.

**Comment by tuxtof** [comment]
ok i find a bug in redhat installer who cause the ks file you send to to failed on my side
if EOL sequence is CRLF pre part failed , crazy

let me make more test with your approach and the pre part to try to reproduce

Concerning your last comment 
On Nutanix API call yes  you can specify id, but no controller as there is no controller logic in AHV.

From Packer side id are automatically assigned based on your declaration order in your conf file, so except if there is a bug in packer who randomize the config file, there is no reason it change

**Comment by tuxtof** [comment]
i already test it 3x time witthout any issue , strange

can you give me your PC and PE version ?

can you also try to failed it again
once done, switch to shell with ctrl + alt + f2

give me output of /tmp/ks*.log
and also the following command

blkid | grep sd
pvs
vgs
lvs

thanks

**Comment by darthVikes** [comment]
Sory for the very long delay, but I was able to duplicate this once again in a totally different nutanix environment. 

Prism Central Version: pc.2023.4.0.2
AHV: el7.nutanix.20220304.488
AOS: 6.5.5.7

I should have noticed this before but if you go into #5 you can see the drives or ordered wrong;

![image](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/assets/12534245/eb06dd9f-600e-43b0-ad56-41e5fd8e293c)

**Comment by darthVikes** [comment]
![image](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/assets/12534245/14e1da36-bfca-4dac-a48e-49686b0c105f)

**Comment by darthVikes** [comment]
![image](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/assets/12534245/3ee8146f-818f-4c93-b91e-c86310dee4f7)

**Comment by darthVikes** [comment]
![image](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/assets/12534245/22703bab-f715-44ad-a15a-527ea408ef33)

**Comment by darthVikes** [comment]
![image](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/assets/12534245/26304d07-ce65-4138-836e-0b4eda695edc)

**Comment by darthVikes** [comment]
Odd.  So for some reason, it's switching sda/sdb around for SCSI 0 & 1.

**Comment by darthVikes** [comment]
Other strange issue is that the 'reboot --eject'  part of the kickstart doesn't eject the ISO?

**Comment by darthVikes** [comment]
So with the above Nutanix seems to be at least consistent with next drive per the config in the template.  Its something on the kickstart side that is not aligning what should be on sda to be  0:0 and sdb to be 0:1 and sdc to be 0:3.   So I modified the kickstart as you did and I removed the separate set up from pre and went back to what you were saying and still seemed to get the result I am looking for with regards to having sdb, sdc NOT using partitions.   see next screenshot.

**Comment by darthVikes** [comment]
![image](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/assets/12534245/91f2bc6a-3137-4f0a-9048-a38320e5bd82)

**Comment by darthVikes** [comment]
I would like to request that functionality enhancement for being able to add a disk to a specific scsi id ]  0-4:0-15 ]   Where the first digit is controller #, and the second # is the SCSI id.    That way you can spread IO load over multiple controllers and lign up a specific drive to a specific scsi id so that in the OS side you can match up your drive letter or mount point if Linux.   This solves an issue with designing standard OS configurations and what SCSI ID they should be on.   aka You would know for SQL server specific drive letters  or mounts is always going to be on a specific SCSI ID.

**Comment by darthVikes** [comment]
Thanks for the input on this issue.
