### ISSUE TITLE
Static IP support

### ISSUE THREAD

**Issue by benjamin-crill** [nutanix-cloud-native/packer-plugin-nutanix#157]
/kind feature

**Describe the solution you'd like**
Would like to have parameter(s) to support setting a static IP for a VM without having to do an unattend.xml sysprep file

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- packer-plugin-nutanix version (use `packer plugins installed`): 
- Packer version (use `packer version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by tuxtof** [comment]
we can implement the IPAM network static address feature => I add it in the roadmap

just by curiosity what is the use case ?

**Comment by benjamin-crill** [comment]
This would be to set a static IP without having to use a Prism IPAM managed network.  Currently need to use sysprep to set static IP.  Would be advantageous to make it native to the plugin.

**Comment by tuxtof** [comment]
How do you want we set the ip of a vm without using an ip managed network or using a sysprep/cloud-init ???

and for my knowledge can you give an exemple where a static ip can be useful for a image build workflow thanks

**Comment by benjamin-crill** [comment]
Apologies, I thought I was requesting this for the terraform provider.
