### ISSUE TITLE
Ubuntu 20.04, 22.04, 23.04 Live Server ISO is ignoring or not detecting the cloud-init config-2 drive

### ISSUE THREAD

**Issue by rolffujino** [nutanix-cloud-native/packer-plugin-nutanix#160]
/kind bug

**What steps did you take and what happened:**
When trying to generate an Ubuntu 22.04 LTS image using packer and Nutanix, from the ubuntu-22.04.3-live-server-amd64 ISO using cloud-init user_data with autoinstall, it never finds the cloud-init configs, times out and goes to the GUI installer.

Packer trace logs just shows that packer is waiting on an IP address and no information of importance.

**What did you expect to happen:**
When using packer with VMware to do the same thing, it discovers the cloud-init configs and performs an autoinstall.

**Anything else you would like to add:**
When you go into the grub command line and list devices (`ls -l`) the CDROM drive from Nutanix for the cloud-init config-2 drive is not shown/accessible.
It is only accessible/visible after running `nativedisk` command, however the contents are following cloud-init standards and valid json, yaml and subiquity:
![image](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/assets/27324676/4e389d99-e768-43f6-9473-e0f21699e8e7)
![image](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/assets/27324676/1fa1c184-bd2a-40bc-8c52-072b74f697fc)
![image](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/assets/27324676/f7873b50-6dd0-4794-b32b-053441e6ad4c)
![image](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/assets/27324676/91510302-c2c8-46e2-a514-029a37cb4dd7)

This issue is not limited to Nutanix packer plugin, it also occurs when using custom script through the GUI in Nutanix and manually adding a CDROM with an ISO with the cloud-init config drive contents.

The cloud-init works when using the ubuntu-22.04-server-cloudimg-amd64 but since the OS is already installed, it prevents customisation of partition tables etc.

**Environment:**

- packer-plugin-nutanix version (use `packer plugins installed`): packer-plugin-nutanix_v0.8.1_x5.0_linux_amd64
- Packer version (use `packer version`): Packer v1.9.4
- OS (e.g. from `/etc/os-release`): 22.04.2 LTS (Jammy Jellyfish)

**Comment by tuxtof** [comment]
Hello @rolffujino 

there is few errors in the method you try to use

- Ubuntu autoinstall mode use by the NoCloud cloud-init datasource as mentioned in the official doc here https://ubuntu.com/server/docs/install/autoinstall
- Nutanix AHV is using the Config Drive v2 datasource, this is the reason why you boot times out and goes to the GUI installer. To use it you need to specify the right format with the ds="configdrive" append arg

You can also use the autoinstall arg to skip confirmation.

And if you want a full e2e automatic experience , as we don't support yet the `boot_cmd` in packer , best is to switch to a netboot install so you can modify your grub/pxe config at the source and add autoinstall and correct ds mode
