### ISSUE TITLE
Packer Crashes on nutanix.windows unexpected EOF

### ISSUE THREAD

**Issue by ktinthecloud** [nutanix-cloud-native/packer-plugin-nutanix#17]
The temporary packer iso is uploaded, but then packer crashes.  See crash.log below:

`2022/07/26 09:31:10 [INFO] Packer version: 1.8.2 [go1.17.11 linux amd64]
2022/07/26 09:31:10 [TRACE] discovering plugins in /usr/bin
2022/07/26 09:31:11 [TRACE] discovering plugins in /home/user@hostname.com/.config/packer/plugins
2022/07/26 09:31:11 [DEBUG] Discovered plugin: nutanix = /home/user@hostname.com/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64
2022/07/26 09:31:11 [INFO] found external [-packer-default-plugin-name-] builders from nutanix plugin
2022/07/26 09:31:11 [TRACE] discovering plugins in .
2022/07/26 09:31:11 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2022/07/26 09:31:11 [INFO] PACKER_CONFIG env var set; attempting to open config file: /home/user@hostname.com/.packerconfig
2022/07/26 09:31:11 [WARN] Config file doesn't exist: /home/user@hostname.com/.packerconfig
2022/07/26 09:31:11 [INFO] Setting cache directory: /home/user@hostname.com/.cache/packer
2022/07/26 09:31:11 [TRACE] listing potential installations for "github.com/nutanix-cloud-native/nutanix" that match ">= 0.1.0". plugingetter.ListInstallationsOptions{FromFolders:[]string{"/usr/bin/packer", ".", "/home/user@hostname.com/.config/packer/plugins"}, BinaryInstallationOptions:plugingetter.BinaryInstallationOptions{APIVersionMajor:"5", APIVersionMinor:"0", OS:"linux", ARCH:"amd64", Ext:"", Checksummers:[]plugingetter.Checksummer{plugingetter.Checksummer{Type:"sha256", Hash:(*sha256.digest)(0xc000540100)}}}}
2022/07/26 09:31:11 [TRACE] Found the following "github.com/nutanix-cloud-native/nutanix" installations: [{/home/user@hostname.com/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 v0.1.1}]
2022/07/26 09:31:11 [INFO] found external [-packer-default-plugin-name-] builders from nutanix plugin
2022/07/26 09:31:11 [TRACE] validateValue: not active for nutanix_password, so skipping
2022/07/26 09:31:11 [TRACE] validateValue: not active for nutanix_port, so skipping
2022/07/26 09:31:11 [TRACE] validateValue: not active for nutanix_cluster, so skipping
2022/07/26 09:31:11 [TRACE] validateValue: not active for virtio_iso_image_name, so skipping
2022/07/26 09:31:11 [TRACE] validateValue: not active for nutanix_username, so skipping
2022/07/26 09:31:11 [TRACE] validateValue: not active for nutanix_endpoint, so skipping
2022/07/26 09:31:11 [TRACE] validateValue: not active for nutanix_insecure, so skipping
2022/07/26 09:31:11 [TRACE] validateValue: not active for nutanix_subnet, so skipping
2022/07/26 09:31:11 [TRACE] validateValue: not active for centos_iso_image_name, so skipping
2022/07/26 09:31:11 [TRACE] validateValue: not active for centos_disk_image_name, so skipping
2022/07/26 09:31:11 [TRACE] validateValue: not active for windows_2016_iso_image_name, so skipping
2022/07/26 09:31:11 [TRACE] Starting external plugin /home/user@hostname.com/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 start builder -packer-default-plugin-name-
2022/07/26 09:31:11 Starting plugin: /home/user@hostname.com/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 []string{"/home/user@hostname.com/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64", "start", "builder", "-packer-default-plugin-name-"}
2022/07/26 09:31:11 Waiting for RPC address for: /home/user@hostname.com/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64
2022/07/26 09:31:11 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:11 Plugin address: unix /tmp/packer-plugin124872568
2022/07/26 09:31:11 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:11 Waiting for connection...
2022/07/26 09:31:11 Received unix RPC address for /home/user@hostname.com/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64: addr is /tmp/packer-plugin124872568
2022/07/26 09:31:11 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:11 Serving a plugin connection...
2022/07/26 09:31:11 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:11 [TRACE] starting builder -packer-default-plugin-name-
2022/07/26 09:31:11 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:11 No Nutanix Port configured, defaulting to '9440'
2022/07/26 09:31:11 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:11 No vmname assigned, setting to Packer-Y8VJTH7X
2022/07/26 09:31:11 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:11 SSHPort not set, defaulting to 22
2022/07/26 09:31:11 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:11 SSHTimeout not set, defaulting to 20min
2022/07/26 09:31:11 [TRACE] Starting internal plugin packer-provisioner-powershell
2022/07/26 09:31:11 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-powershell"}
2022/07/26 09:31:11 Waiting for RPC address for: /usr/bin/packer
2022/07/26 09:31:11 packer-provisioner-powershell plugin: [INFO] Packer version: 1.8.2 [go1.17.11 linux amd64]
2022/07/26 09:31:11 packer-provisioner-powershell plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2022/07/26 09:31:11 packer-provisioner-powershell plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /home/user@hostname.com/.packerconfig
2022/07/26 09:31:11 packer-provisioner-powershell plugin: [WARN] Config file doesn't exist: /home/user@hostname.com/.packerconfig
2022/07/26 09:31:11 packer-provisioner-powershell plugin: [INFO] Setting cache directory: /home/user@hostname.com/.cache/packer
2022/07/26 09:31:11 packer-provisioner-powershell plugin: args: []string{"packer-provisioner-powershell"}
2022/07/26 09:31:11 packer-provisioner-powershell plugin: Plugin address: unix /tmp/packer-plugin1231543871
2022/07/26 09:31:11 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin1231543871
2022/07/26 09:31:11 packer-provisioner-powershell plugin: Waiting for connection...
2022/07/26 09:31:11 packer-provisioner-powershell plugin: Serving a plugin connection...
2022/07/26 09:31:11 [TRACE] Starting internal plugin packer-provisioner-windows-restart
2022/07/26 09:31:11 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-windows-restart"}
2022/07/26 09:31:11 Waiting for RPC address for: /usr/bin/packer
2022/07/26 09:31:11 packer-provisioner-windows-restart plugin: [INFO] Packer version: 1.8.2 [go1.17.11 linux amd64]
2022/07/26 09:31:11 packer-provisioner-windows-restart plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2022/07/26 09:31:11 packer-provisioner-windows-restart plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /home/user@hostname.com/.packerconfig
2022/07/26 09:31:11 packer-provisioner-windows-restart plugin: [WARN] Config file doesn't exist: /home/user@hostname.com/.packerconfig
2022/07/26 09:31:11 packer-provisioner-windows-restart plugin: [INFO] Setting cache directory: /home/user@hostname.com/.cache/packer
2022/07/26 09:31:11 packer-provisioner-windows-restart plugin: args: []string{"packer-provisioner-windows-restart"}
2022/07/26 09:31:11 packer-provisioner-windows-restart plugin: Plugin address: unix /tmp/packer-plugin4042051756
2022/07/26 09:31:11 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin4042051756
2022/07/26 09:31:11 packer-provisioner-windows-restart plugin: Waiting for connection...
2022/07/26 09:31:11 packer-provisioner-windows-restart plugin: Serving a plugin connection...
2022/07/26 09:31:11 ui: Debug mode enabled. Builds will not be parallelized.
2022/07/26 09:31:11 ui: [1;32mnutanix.windows: output will be in this color.[0m
2022/07/26 09:31:11 ui: 
2022/07/26 09:31:11 Build debug mode: true
2022/07/26 09:31:11 Force build: false
2022/07/26 09:31:11 On error: 
2022/07/26 09:31:11 Debug enabled, so waiting for build to finish: nutanix.windows
2022/07/26 09:31:11 Starting build run: nutanix.windows
2022/07/26 09:31:11 Running builder: 
2022/07/26 09:31:11 [INFO] (telemetry) Starting builder nutanix.windows
2022/07/26 09:31:11 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:11 PC Host from config: prismcentral.hostname.com
2022/07/26 09:31:11 ui: [1;32m==> nutanix.windows: Creating CD disk...[0m
2022/07/26 09:31:11 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:11 CD path: /tmp/packer2821361394.iso
2022/07/26 09:31:11 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:11 Wrote 14139 bytes to autounattend.xml
2022/07/26 09:31:11 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:11 Wrote 3697 bytes to win-update.ps1
2022/07/26 09:31:11 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:11 Executing: /usr/bin/xorriso [-as genisoimage -rock -joliet -volid packer -output /tmp/packer2821361394.iso /tmp/packer_to_cdrom3869812291]
2022/07/26 09:31:11 ui: [0;32m    nutanix.windows: xorriso 1.5.2 : RockRidge filesystem manipulator, libburnia project.[0m
2022/07/26 09:31:11 ui: [0;32m    nutanix.windows: Drive current: -outdev 'stdio:/tmp/packer2821361394.iso'[0m
2022/07/26 09:31:11 ui: [0;32m    nutanix.windows: Media current: stdio file, overwriteable[0m
2022/07/26 09:31:11 ui: [0;32m    nutanix.windows: Media status : is blank[0m
2022/07/26 09:31:11 ui: [0;32m    nutanix.windows: Media summary: 0 sessions, 0 data blocks, 0 data, 29.3g free[0m
2022/07/26 09:31:11 ui: [0;32m    nutanix.windows: xorriso : WARNING : -volid text does not comply to ISO 9660 / ECMA 119 rules[0m
2022/07/26 09:31:11 ui: [0;32m    nutanix.windows: Added to ISO image: directory '/'='/tmp/packer_to_cdrom3869812291'[0m
2022/07/26 09:31:11 ui: [0;32m    nutanix.windows: xorriso : UPDATE :       2 files added in 1 seconds[0m
2022/07/26 09:31:11 ui: [0;32m    nutanix.windows: xorriso : UPDATE :       2 files added in 1 seconds[0m
2022/07/26 09:31:11 ui: [0;32m    nutanix.windows: ISO image produced: 192 sectors[0m
2022/07/26 09:31:11 ui: [0;32m    nutanix.windows: Written to medium : 192 sectors at LBA 0[0m
2022/07/26 09:31:11 ui: [0;32m    nutanix.windows: Writing to 'stdio:/tmp/packer2821361394.iso' completed successfully.[0m
2022/07/26 09:31:11 ui: [0;32m    nutanix.windows: Done copying paths from CD_dirs[0m
2022/07/26 09:31:11 ui: [1;32m==> nutanix.windows: Creating Packer Builder VM on Nutanix Cluster.[0m
2022/07/26 09:31:11 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:11 Check for temporary iso-disks to attach
2022/07/26 09:31:11 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:11 temporary iso found, /tmp/packer2821361394.iso
2022/07/26 09:31:12 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:12 Creating Image: RUNNING
2022/07/26 09:31:17 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:17 Creating Image: RUNNING
2022/07/26 09:31:22 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:22 Creating Image: RUNNING
2022/07/26 09:31:27 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:27 Creating Image: RUNNING
2022/07/26 09:31:32 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:32 Creating Image: COMPLETE
2022/07/26 09:31:46 ui: [1;32m==> nutanix.windows: Temporary ISO uploaded[0m
2022/07/26 09:31:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:48 waiting for vm (a4fe505f-0f59-48e8-ac97-fc2656410dea) to create: dbc89cb6-8866-483a-bda2-65b9155452ba
2022/07/26 09:31:48 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:48 Current status is: RUNNING
2022/07/26 09:31:53 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:53 Current status is: RUNNING
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:59 Nutanix VM UUID: a4fe505f-0f59-48e8-ac97-fc2656410dea
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 2022/07/26 09:31:59 Deleting CD disk: /tmp/packer2821361394.iso
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: panic: runtime error: index out of range [0] with length 0
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: goroutine 20 [running]:
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: github.com/nutanix-cloud-native/packer-plugin-nutanix/builder/nutanix.(*nutanixInstance).Addresses(0xc0004c8090)
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 	github.com/nutanix-cloud-native/packer-plugin-nutanix/builder/nutanix/driver.go:144 +0x131
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: github.com/nutanix-cloud-native/packer-plugin-nutanix/builder/nutanix.(*stepBuildVM).Run(0xc000088190, {0xf63754, 0x0}, {0x117ae78, 0xc0004c8090})
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 	github.com/nutanix-cloud-native/packer-plugin-nutanix/builder/nutanix/step_build_vm.go:60 +0x6fe
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: github.com/hashicorp/packer-plugin-sdk/multistep.(*BasicRunner).Run(0xc0004c80f0, {0x117a9a8, 0xc00001c0c0}, {0x117ae78, 0xc0004c8090})
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 	github.com/hashicorp/packer-plugin-sdk@v0.3.0/multistep/basic_runner.go:70 +0x2fe
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: github.com/nutanix-cloud-native/packer-plugin-nutanix/builder/nutanix.(*Builder).Run(0xc0002bf400, {0x117a9a8, 0xc00001c0c0}, {0x1181fa0, 0xc0004c8060}, {0x11602a0, 0xc000300040})
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 	github.com/nutanix-cloud-native/packer-plugin-nutanix/builder/nutanix/builder.go:81 +0x655
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: github.com/hashicorp/packer-plugin-sdk/rpc.(*BuilderServer).Run(0xc000311ec0, 0x34110, 0xc0000340b0)
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 	github.com/hashicorp/packer-plugin-sdk@v0.3.0/rpc/builder.go:117 +0x1e3
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: reflect.Value.call({0xc00007ea80, 0xc00000e720, 0x13}, {0xf5d8bb, 0x4}, {0xc0003a2ef8, 0x3, 0x3})
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 	reflect/value.go:556 +0x845
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: reflect.Value.Call({0xc00007ea80, 0xc00000e720, 0xc000101000}, {0xc0003dc6f8, 0x3, 0x3})
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 	reflect/value.go:339 +0xc5
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: net/rpc.(*service).call(0xc000311f00, 0xc000498ecc, 0x0, 0xc000034620, 0xc0000f4580, 0x5ee2e5, {0xdc2940, 0xc00003408c, 0x5ee266}, {0xda4ca0, ...}, ...)
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 	net/rpc/server.go:377 +0x239
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: created by net/rpc.(*Server).ServeCodec
2022/07/26 09:31:59 packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64 plugin: 	net/rpc/server.go:474 +0x405
2022/07/26 09:31:59 [INFO] (telemetry) ending nutanix.windows
2022/07/26 09:31:59 /home/user@hostname.com/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.1.1_x5.0_linux_amd64: plugin process exited
2022/07/26 09:31:59 ui error: [1;31mBuild 'nutanix.windows' errored after 47 seconds 921 milliseconds: unexpected EOF[0m
2022/07/26 09:31:59 Waiting on builds to complete...
2022/07/26 09:31:59 ui: 
==> Wait completed after 47 seconds 921 milliseconds
2022/07/26 09:31:59 machine readable: error-count []string{"1"}
2022/07/26 09:31:59 ui error: 
==> Some builds didn't complete successfully and had errors:
2022/07/26 09:31:59 machine readable: nutanix.windows,error []string{"unexpected EOF"}
2022/07/26 09:31:59 ui error: --> nutanix.windows: unexpected EOF
2022/07/26 09:31:59 ui: 
==> Builds finished but no artifacts were created.
2022/07/26 09:31:59 [INFO] (telemetry) Finalizing.
2022/07/26 09:31:59 waiting for all plugin processes to complete...
2022/07/26 09:31:59 /usr/bin/packer: plugin process exited
2022/07/26 09:31:59 /usr/bin/packer: plugin process exited
`

**Comment by wolfganghuse** [comment]
@ktinthecloud Are you using AHV IPAM for IP-Assignment or external DHCP ?
There is a known Issue when using external DHCP, we will address this very soon.
 
As a workaround you can use an IPAM-enabled subnet.

**Comment by tuxtof** [comment]
@ktinthecloud we just release 0.1.3 with Non IPAM network support, binary will eb available in few minutes

**Comment by ktinthecloud** [comment]
@wolfganghuse & @tuxtof - I turned IPAM on and it works.  Thanks!

**Comment by wolfganghuse** [comment]
Thanks for letting us know... 0.1.3 will now also work in DHCP-Subnets...
