### ISSUE TITLE
 'reboot --eject'  part of the kickstart script doesn't eject the ISO?

### ISSUE THREAD

**Issue by darthVikes** [nutanix-cloud-native/packer-plugin-nutanix#190]
'reboot --eject'  part of the kickstart script doesn't eject the ISO?

_Originally posted by @darthVikes in https://github.com/nutanix-cloud-native/packer-plugin-nutanix/issues/152#issuecomment-2173411735_

**Comment by PS1c0m** [comment]
Same issue https://github.com/nutanix-cloud-native/packer-plugin-nutanix/issues/194

**Comment by darthVikes** [comment]
This one was opened first =)   but I will close it as dupe.
