### ISSUE TITLE
Kickstart files are not ingested by ISO installation when building from arm64 plugin

### ISSUE THREAD

**Issue by kingsleyck-ntnx** [nutanix-cloud-native/packer-plugin-nutanix#195]
/kind bug

**What steps did you take and what happened:**

I created a repo to build a source VM from Rocky Linux 8.8 using the minimal ISO. The kickstart file is created with cd_content specified. The ISO creates successfully and is also correctly attached to the VM. However, the VM behavior is incorrect. The VM boots into GUI setup ignoring the ks.cfg.

The exact same code functions correctly if it uses the Linux VM plugin, ex: packer-plugin-nutanix_v0.9.0_x5.0_linux_amd64

It appears there is a bug in the latest arm64 plugin.

**What did you expect to happen:**

VM should boot and start text based install using the supplied ks.cfg.

**Anything else you would like to add:**

N/A

**Environment:**

- packer-plugin-nutanix version (use `packer plugins installed`): packer-plugin-nutanix_v0.9.0_x5.0_darwin_arm64
- Packer version (use `packer version`): v1.11.2
- OS (e.g. from `/etc/os-release`): Sonoma 14.5

**Comment by tuxtof** [comment]
Hello @kingsleyck-ntnx 

did you correctly name your kickstart ISO image to allow installer to autoboot your kickstart

exemple here https://github.com/nutanix-cloud-native/packer-plugin-nutanix/blob/main/test/e2e/centos-iso/source.pkr.hcl

cd_files & cd_labels

**Comment by tuxtof** [comment]
Hello @kingsleyck-ntnx can you share log of the build process please

**Comment by tuxtof** [comment]
i just test it with same packer + plugin version and updated OS 15.0, no issue on my side

**Comment by kingsleyck-ntnx** [comment]
I'm using cd_content for this use case because the file has to be retrieved first using the http data provider.

Example:  

data "http" "ks" {
  url = "http://<webhost>/ks.cfg>"
}

source "nutanix" "linux_iso" {
....
  cd_content          = {
    "${var.template_dst_file}" = data.http.ks.body
  }
....
}

This works on the linux plugin with no other code change.

**Comment by tuxtof** [comment]
duplicate #91

**Comment by kingsleyck-ntnx** [comment]
Root cause was using native hdiutil on MacOS to create the kickstart ISO. Use xorriso instead. Thanks @tuxtof for the assist.
