### ISSUE TITLE
Windows VM build in setup boot loop

### ISSUE THREAD

**Issue by ktinthecloud** [nutanix-cloud-native/packer-plugin-nutanix#205]
After upgrading AOS to 6.5.6.6 and PC to 2023.4.0.2 I've noticed that my windows packer builds are breaking.  The packer VM goes into setup and successfully finishes the OS install, but then reboots and goes back into setup and the process repeats in an endless loop.  

Looks like the OS ISO is not being ejected from the VM after setup finishes and the VM is rebooted.  If I eject the ISO manually the build finishes successfully.

Also, my Ubuntu builds are still working fine.  Any way to fix the windows builds?

**Comment by Peter1295** [comment]
Hello, in my case issue was that the ISO was generated on the legacy boot, change it to UEFI -> _**boot_type = "uefi"**_ (it's case sensitive) and make sure you have proper Autounattend.xml file with UEFI disk configuration, I have used as template this [one ](https://gist.github.com/bohack/91fb9d2d024c6f2ec1b13b1d0fce1380)

**Comment by ktinthecloud** [comment]
After upgrading to AOS 6.10 and PC 2024.2 this is no longer an issue.

**Comment by tuxtof** [comment]
thanks for the update @ktinthecloud
