### ISSUE TITLE
Unable to connect to the remote server

### ISSUE THREAD

**Issue by ktinthecloud** [nutanix-cloud-native/packer-plugin-nutanix#27]
Looks like it's trying to download a powershell script, but it fails on "Unable to connect to the remote server".  Is this communication from the temporary Packer VM back to the server that I'm running Packer from?

==> nutanix.windows: Connected to WinRM!
==> nutanix.windows: Pausing 2m0s before the next provisioner...
==> nutanix.windows: Provisioning with Powershell...
==> nutanix.windows: Provisioning with powershell script: scripts/win-update.ps1
    nutanix.windows: Starting PSWindowsUpdate Installation
    nutanix.windows: Ended PSWindowsUpdate Installation
    nutanix.windows: Starting Windows Update Installation
==> nutanix.windows: **Exception calling "DownloadFile" with "2" argument(s): "Unable to connect to the remote server"**
==> nutanix.windows: At C:\Windows\Temp\script-62e169c3-de72-34c5-129c-a1e2ef059275.ps1:11 char:1
==> nutanix.windows: + (New-Object System.Net.WebClient).DownloadFile($webDeployURL, $filePa ...
==> nutanix.windows: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> nutanix.windows:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
==> nutanix.windows:     + FullyQualifiedErrorId : WebException
==> nutanix.windows:
==> nutanix.windows: You cannot call a method on a null-valued expression.
==> nutanix.windows: At C:\Windows\Temp\script-62e169c3-de72-34c5-129c-a1e2ef059275.ps1:24 char:1
==> nutanix.windows: + $destinationFolder.CopyHere($zipFile.Items(), $copyFlags)
==> nutanix.windows: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> nutanix.windows:     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
==> nutanix.windows:     + FullyQualifiedErrorId : InvokeMethodOnNull
==> nutanix.windows:
==> nutanix.windows: Remove-Item : Cannot find path 'C:\Users\ADMINI~1\AppData\Local\Temp\PSWindowsUpdate.zip' because it does not exist.
==> nutanix.windows: At C:\Windows\Temp\script-62e169c3-de72-34c5-129c-a1e2ef059275.ps1:26 char:1
==> nutanix.windows: + Remove-Item -Force -Path $filePath
==> nutanix.windows: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> nutanix.windows:     + CategoryInfo          : ObjectNotFound: (C:\Users\ADMINI...ndowsUpdate.zip:String) [Remove-Item], ItemNotFoundEx
==> nutanix.windows:    ception
==> nutanix.windows:     + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
==> nutanix.windows:
==> nutanix.windows: C:\Windows\Temp\script-62e169c3-de72-34c5-129c-a1e2ef059275.ps1 : Unable to install PSWindowsUpdate
==> nutanix.windows: At line:1 char:215
==> nutanix.windows: + ... 923cc2.ps1; &'c:/Windows/Temp/script-62e169c3-de72-34c5-129c-a1e2ef05 ...
==> nutanix.windows: +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> nutanix.windows:     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
==> nutanix.windows:     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,script-62e169c3-de72-34c5-129c-a1e2ef0
==> nutanix.windows:    59275.ps1
==> nutanix.windows:
==> nutanix.windows: Provisioning step had errors: Running the cleanup provisioner, if present...
==> nutanix.windows: Cleaning up Nutanix VM.
Build 'nutanix.windows' errored after 11 minutes 7 seconds: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

==> Wait completed after 11 minutes 7 seconds

==> Some builds didn't complete successfully and had errors:
--> nutanix.windows: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.

**Comment by wolfganghuse** [comment]
This is actual not a failure of packer-plugin but a error-message from the Powershell-Script which runs within the Packer VM to demonstrate Provisioner Steps.
Within the example/scripts folder is a win-update.ps1 script causing this error. The script should have most commands out-commented, did you change something within that script ?

**Comment by ktinthecloud** [comment]
@wolfganghuse - That was it.  I had uncommented out that script as I thought it was needed.  The image has been created successfully.  Thanks so much for your help!
