### ISSUE TITLE
Packer image created as "Legacy BIOS" instead of "UEFI"

### ISSUE THREAD

**Issue by ktinthecloud** [nutanix-cloud-native/packer-plugin-nutanix#28]
When creating a VM from the finished packer image it only boots if you set the Boot Configuration to **Legacy BIOS** when creating the VM.  Is there a way to create a **UEFI** disk image instead?

**Comment by tuxtof** [comment]
Hello @ktinthecloud this is on the roadmap

**Comment by ktinthecloud** [comment]
@tuxtof do you have an ETA?

**Comment by tuxtof** [comment]
@ktinthecloud you can test https://github.com/nutanix-cloud-native/packer-plugin-nutanix/pull/32
