### ISSUE TITLE
Failed to boot from UEFI

### ISSUE THREAD

**Issue by ktinthecloud** [nutanix-cloud-native/packer-plugin-nutanix#33]
I'm testing out v0.2.0 new UEFI feature and after adding `boot_type = "uefi"` to the **source.nutanix.pkr.hcl** file it gets to the point where it uploads the packer image and creates a UEFI temporary packer VM, but it fails to boot.  I tried modifying the **autounattend.xml** file also, but it still fails.  

Have you guys gotten this to work in your lab?  Can you provide a sample **autounattend.xml** and **source.nutanix.pkr.hcl**?

Thanks!

**Comment by wolfganghuse** [comment]
Can you provide more details to whats happening, failure while boot and used Windows Version ? 
Win2016 ISOs as example needs to be remastered with `efisys_noprompt.bin` otherwise already booting from ISO won´t work in an automated fashion as you would need to hit any key.

**Comment by ktinthecloud** [comment]
I tried it with 2019 also.  Initially I get the following error:
![image](https://user-images.githubusercontent.com/63941280/182181087-be29303e-066d-4cab-b62c-77da3d1b5485.png)

After some time I get this error:
![image](https://user-images.githubusercontent.com/63941280/182181354-ef4d5d50-1d08-4450-9e1f-ca713237223e.png)

Here's the packer output:
![image](https://user-images.githubusercontent.com/63941280/182182001-ab14e1a5-b9f0-4e9a-82a9-cbcc6882fba6.png)

Attached are the **build.centos.pkr.hcl** and the **source.nutanix.pkr.hcl**

[packer_build_and_source_files.zip](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/files/9235168/packer_build_and_source_files.zip)

**Comment by wolfganghuse** [comment]
This is nothing we can influence... see this post as example: [https://taylor.dev/removing-press-any-key-prompts-for-windows-install-automation/](url)
If you manually press any key you can check your unattended.xml... you need a UEFI Diskconfiguration and keep in mind to change the InstallTo Partitionnumber to 3 (i guess)

**Comment by ktinthecloud** [comment]
Thanks @wolfganghuse.  Looks like it's working now.  I used this powershell script to create the "no prompt" Windows ISO: https://www.deploymentresearch.com/a-good-iso-file-is-a-quiet-iso-file/
