### ISSUE TITLE
Packer Image deployed to wrong Storage Container (SelfServiceContainer)

### ISSUE THREAD

**Issue by ktinthecloud** [nutanix-cloud-native/packer-plugin-nutanix#36]
The Packer images are created on Prism Central and then pushed to the cluster, but they end up on the SelfServiceContainer and there is no option in the WebGUI to move them to a different storage container.  How can I have the images built on a container of my choosing?

**Comment by tuxtof** [comment]
@ktinthecloud that's something who is not available in the Nutanix API for now, so no able to implement it in the Packer plugin.

A workaround is to deplace the VM after his creation with the `acli vm.update_container XXX` command
