### ISSUE TITLE
No artifacts created

### ISSUE THREAD

**Issue by benjamin-crill** [nutanix-cloud-native/packer-plugin-nutanix#43]
Using example HCL file with Windows only section, the file validates, but then on build it says completed with no artifacts

_Miscellaneous information that will assist in solving the issue._

**Environment:** Nutanix CE (PC version 2019.11.22)

- packer-plugin-nutanix version (use `packer plugins installed`): v0.2
- Packer version (use `packer version`): 1.8.3
- OS (e.g. from `/etc/os-release`): Windows 10

**Comment by ktinthecloud** [comment]
@benjamin-crill Are you targeting an IPAM or DHCP enabled subnet?

**Comment by benjamin-crill** [comment]
There is DHCP on the network targeted but it is not controlled via Prism.  Standard MSFT DHCP

**Comment by ktinthecloud** [comment]
I was getting the same error until I enabled IPAM, but I believe the new version is supposed to support DHCP, but I haven't tried it.

**Comment by tuxtof** [comment]
Hello @benjamin-crill 
Can you paste a full trace by launching packer with `PACKER_LOG=1 packer <command> [<args>]`

**Comment by tuxtof** [comment]
@benjamin-crill did you fix your issue ?

**Comment by benjamin-crill** [comment]
Sorry I got pulled away into other things.  Let me try this week and I'll post back

**Comment by benjamin-crill** [comment]
Trying it now it won't even validate.  Getting unknown source errors.  Do you have a working HCL file?  I'm trying to create a Windows image.  
Error: Unknown source nutanix.centos

  on  line 0:
  (source code not available)

Known: []

Error: Unknown source nutanix.centos-kickstart

  on  line 0:
  (source code not available)

Known: []

Error: Unknown source nutanix.windows

  on  line 0:
  (source code not available)

Known: []

**Comment by tuxtof** [comment]
@benjamin-crill you have exemple here https://github.com/nutanix-cloud-native/packer-plugin-nutanix/tree/main/example

**Comment by benjamin-crill** [comment]
That's what I'm using and getting the error above.  I've found some other options.  I like Packer and Nutanix, but so far this hasn't worked at all.  Needs some more polishing and documentation IMO

**Comment by benjamin-crill** [comment]
I tried it with all the CentOS stuff removed as well as the example provided as is.  At this point I'll wait for improved documentation.
