### ISSUE TITLE
Add Ubuntu builder

### ISSUE THREAD

**Issue by ktinthecloud** [nutanix-cloud-native/packer-plugin-nutanix#47]
Looks like there is a centos and a windows builder, but not an Ubuntu builder.  Can you please add an Ubuntu builder?  Thanks!

`build {
  sources = [
    "source.nutanix.centos"
  ]
  
  source "nutanix.centos-kickstart" {
    name = "centos-kickstart"
  }
  source "nutanix.windows" {
    name = "windows"
  }`

**Comment by wolfganghuse** [comment]
Ubuntu may be used like any other environment. Limitation may be that Ubuntu ISO Boot does not support OEMDRV ignition files. But you may be able to start from cloud image…
What’s your preferred way to build on top of Ubuntu?

**Comment by ktinthecloud** [comment]
I see.  I was going to try the cloud-unit auto install outlined here: https://ubuntu.com/server/docs/install/autoinstall

I'll see if I can figure it out.  Thanks.

**Comment by ktinthecloud** [comment]
I think I'm on the right path by following the centos example.  Closing this issue out.
