### ISSUE TITLE
Add boot_command and boot_wait to Ubuntu Subiquity autoinstall builds

### ISSUE THREAD

**Issue by ktinthecloud** [nutanix-cloud-native/packer-plugin-nutanix#49]
I'm attempting to create Ubuntu 20.04 packer builds using Subiquity.  The temporary packer.iso is created and so is the packer vm, but it hangs at the following spot:

![image](https://user-images.githubusercontent.com/63941280/186771659-594bce02-9a77-4f26-9f78-e7d151e96228.png)

Looks like other plugins have the **`boot_command`** and **`boot_wait`** options to deal with this. https://askubuntu.com/questions/1385563/packer-ubuntu-server-20-04-prompting-for-install-confirmation-despite-autoinsta

Can these options be added to this plugin?
![image](https://user-images.githubusercontent.com/63941280/186772432-799e501b-82d8-4ca3-871c-5ed5b14c1980.png)

Or maybe there is a better way to handle auto installs of Ubuntu?  Do you guys have a working example of an Ubuntu build?

**Comment by ktinthecloud** [comment]
Support ticket has been opened with Nutanix support.

**Comment by tandrez** [comment]
Hello. I'm also interested by this feature. Any update from the support case?

**Comment by tuxtof** [comment]
> Hello. I'm also interested by this feature. Any update from the support case?

@tandrez can you create your own ticket to prioritize the feature and give the ticket number here

thanks

**Comment by ktinthecloud** [comment]
> > Support ticket has been opened with Nutanix support.
> 
> @ktinthecloud can you paste you support ticket reference here please

CASE 01276838

It was closed out with the response below:

Currently, there is no official/supported way to use boot_command or boot_wait options. Hopefully engineering will expose some sort of API layer or access to noVNC in the feature request.

Thank you,


To view case history Click here : https://portal.nutanix.com/page/smart-support/case/details?id=5007V000026d22FQAQ


Jason Tupper | Systems Reliability Engineer | Nutanix | 1-855-NUTANIX Ext 3
Business Hours: Mon - Fri 08:00 - 16:00 EDT
Customer Support Portal: http://portal.nutanix.com/
ref:_00D60IUGi._5007V26d22F:ref

**Comment by ktinthecloud** [comment]
> > Support ticket has been opened with Nutanix support.
> 
> @ktinthecloud can you paste you support ticket reference here please

New ticket opened: 01524228

**Comment by mikedonleyuoy** [comment]
I have raised this with Nutanix support - they have issued FEAT-16277 feature request for anyone who wants to track it/add their +1

**Comment by tuxtof** [comment]
Hello @mikedonleyuoy @ktinthecloud @tandrez 

we’ve decided to implement this feature using an internal method for now. We're preparing a tech preview, if you're interested in exploring it or providing feedback, feel free to reach out to me at christophe.jauffret@nutanix.com
