### ISSUE TITLE
Unable to build windows image on Nutanix using plugin

### ISSUE THREAD

**Issue by vivekdabas** [nutanix-cloud-native/packer-plugin-nutanix#77]
/kind bug

**What steps did you take and what happened:**

We used the packer plugin code, and tweaked the values and variables to match our environment. However,  running the `packer build` command throws an error. The error is mentioned below:

`nutanix.windows: output will be in this color.

==> nutanix.windows: Creating CD disk...
Build 'nutanix.windows' errored after 397 milliseconds 738 microseconds: could not find a supported CD ISO creation command (the supported commands are: xorriso, mkisofs, hdiutil, oscdimg)

==> Wait completed after 397 milliseconds 738 microseconds

==> Some builds didn't complete successfully and had errors:
--> nutanix.windows: could not find a supported CD ISO creation command (the supported commands are: xorriso, mkisofs, hdiutil, oscdimg)

==> Builds finished but no artifacts were created.
`

I have already installed OSCDIMG utility and added into the windows PATH variables. If I execute oscdimg from command prompt, gets the below output

`PS C:\Users\vivek.dabas> oscdimg

OSCDIMG 2.54 CD-ROM and DVD-ROM Premastering Utility
Copyright (C) Microsoft, 1993-2007. All rights reserved.
Licensed only for producing Microsoft authorized content.

Usage: OSCDIMG [options] sourceroot targetfile

For option information, use -help with one of the following categories
        ISO      Options for the ISO 9660 file system
        Joliet   Options for the Joliet file system
        UDF      Options for the UDF file system
        Boot     Options for bootable CDs
        Optimize Options for optimization
        Order    Options for ordering the files
        DVD      Options for DVD video and audio
        Mesg     Options for displaying warnings and messages
        Other    Options that do not fit in any other category`

**What did you expect to happen:**
I expect to run the _packer build_ command to build the ISO for Nutanix environment.

**Anything else you would like to add:**
packer has been initialized with the plugin.

_Miscellaneous information that will assist in solving the issue._
I have attached the zipped code along with the log files.

**Environment:**

- packer-plugin-nutanix version (use `packer plugins installed`): C:\Users\vivek.dabas\AppData\Roaming\packer.d\plugins\github.com\nutanix-cloud-native\nutanix\packer-plugin-nutanix_v0.3.0_x5.0_windows_386.exe
- Packer version (use `packer version`): 1.8.0
- OS (e.g. from `/etc/os-release`): Windows 10
[test-packer-nutanix-plugin-main.zip](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/files/10197232/test-packer-nutanix-plugin-main.zip)

**Comment by vivekdabas** [comment]
Getting the error, attached in the screenshot, while trying to build the image on an Ubuntu server, using the same code.

![Packer_Ubuntu_Error](https://user-images.githubusercontent.com/26025867/207388131-c5fe68d9-ec7e-4d44-aedb-0594ff8ac24e.jpg)

**Comment by tuxtof** [comment]
hello @vivekdabas now this is a different error
and this one is more related to Nutanix :-D

it seems you are using the default certificate on your Prism Central or a badly created
in this case you can try to set your `nutanix_insecure` flag to true and it will fix your issue here

this is a short term fix, best is to properly set a certificate on your PC

**Comment by vivekdabas** [comment]
Hi @tuxtof,

After setting the flag `nutanix_insecure` to true, we were able to communicate with PC, however got the new set of error. I was wondering is there any way we can attach an `.ini` or `sysprep` file to the code. 
![Packer_Ubuntu_Error1](https://user-images.githubusercontent.com/26025867/208177904-f0897665-c0d9-48c2-96e7-b29c4c6f2fb5.jpg)

**Comment by tuxtof** [comment]
Hello @vivekdabas 
based on your last error, seems VM are not able to retrieve an IP.

you need to configure you windows env to boot and get network connection correctly and also set your network (IPAM or dhcp) accordingly

Did you look the example here https://github.com/nutanix-cloud-native/packer-plugin-nutanix/blob/main/example/source.nutanix.pkr.hcl

files are passed with a CD

`cd_files         = ["scripts/gui/autounattend.xml","scripts/win-update.ps1"]`

**Comment by vivekdabas** [comment]
Hi @tuxtof,

After resolving the IP address issue, we encountered another set of error. Attaching the screenshot and log files for your reference. Could you assist further?
![Packer New Error](https://user-images.githubusercontent.com/26025867/208498348-995ecd99-6d62-4575-9afe-a48ef4b193f8.jpg)
[packerlog_VMEntity_found.txt](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/files/10261925/packerlog_VMEntity_found.txt)

**Comment by tuxtof** [comment]
Hi @vivekdabas 

it seems there isa vm creation issue , can you check in prism The recent task view and search for a CreateVM task in error

**Comment by vivekdabas** [comment]
Hi @tuxtof,

Made some progress, however, ran into another error. 😅 
Attaching the screenshot of the latest error. I have checked with the Firewall team and they confirmed traffic is flowing from my machine to Nutanix PC on port 5986 (WinRM). Any suggestion, what could be tried next. 
![Packer New Error4 jpg](https://user-images.githubusercontent.com/26025867/209019686-8475774e-f0fb-49eb-a149-1d657ab9e7c2.png)

**Comment by tuxtof** [comment]
Hi @vivekdabas 

now this is a windwos issue, Winrm need to be correctly configured and the machine who run packer/ansible (your laptop ??) need to be able to connect tot he machine (10.179.9.42 here)

the unattented.xml need to be configured correctly , you can start from this example 
https://github.com/nutanix-cloud-native/packer-plugin-nutanix/blob/main/example/scripts/gui/autounattend.xml

and need to be aligned with your packer settings 

exemple like
```
  communicator      = "winrm"
  winrm_port        = 5986
  winrm_insecure    = true
  winrm_use_ssl     = true
  winrm_timeout     = "45m"
  winrm_password    = "packer"
  winrm_username    = "Administrator"
```

did you already succesfully use the window example from the repo ?

**Comment by tuxtof** [comment]
@vivekdabas any news on this one ?

**Comment by hyru-ar** [comment]
HI @tuxtof , thanks a lot for you help, we were able to deploy the Linux image into Nutanix. But we are facing a problem when trying the same for Windows. Apparently and different than with vsphere, copying the sysprep is not the only thing required for the same to be executed, or at least that's what we think. Here is how we are trying:

![image](https://user-images.githubusercontent.com/19286882/212926659-d926b6c4-d064-4b56-95c6-96e6788a86d3.png)

Can you please point us in the right direction? Does it requires to get copy into the server and then executed using a powershell provisioner?

Thanks in advance!

**Comment by tuxtof** [comment]
Hello @hyru-ar 
did you already try succesfully the windows example here https://github.com/nutanix-cloud-native/packer-plugin-nutanix/tree/main/example

the first issue i already see in your example is the name of autounattend file
it need to be `autounattend.xml`

you also need to take care to inject disk and network driver during the boot

**Comment by hyru-ar** [comment]
I've tried using the configuration from the examples, and I'm always getting the same error.

![image](https://user-images.githubusercontent.com/19286882/212980728-adf64bce-cf82-444b-87c3-0b0e3319420b.png)

![image](https://user-images.githubusercontent.com/19286882/212980786-d1a69aaf-37df-486c-aad8-528d9a611ab5.png)

i've also tried adding the TCP and DNS blocks to the example sysprep, giving the correct network values, but still getting the same error.

![image](https://user-images.githubusercontent.com/19286882/212980965-ead62133-fb0a-47a9-993c-e48eee7cd5f4.png)

**Comment by tuxtof** [comment]
can you launch your packer build with 
`PACKER_LOG=1 packer build [<args>]`

and also check inside prism inside the task list i think you have a vm create error

**Comment by hyru-ar** [comment]
![image](https://user-images.githubusercontent.com/19286882/212988393-4042d167-5568-4b01-b203-bd1cf28c229d.png)

[packerlog.txt](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/files/10438504/packerlog.txt)

![image](https://user-images.githubusercontent.com/19286882/212989680-aa8d963a-7bd9-4bcd-a7bd-18701487acc6.png)

**Comment by hyru-ar** [comment]
@tuxtof we are missing this ISO, which I think contains some of the drivers we need:

virtio_iso_image_name = "<name of VirtIO tools iso from the Nutanix image library>"

I've dig into some pages without sucess, can you help me get an ISO for that?

**Comment by tuxtof** [comment]
go here https://portal.nutanix.com/page/downloads?product=ahv
and in the top of the page you have a dropdown list with 

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/180613/213131755-d0fc60b7-be46-4fa2-ad23-350ebbe22fdc.png">

**Comment by hyru-ar** [comment]
Thanks @tuxtof . I've configured everything as in the example, using that virtio iso, another iso for the OS and the additional disk. Using the sysprep and ps1 script from the example as well, but I'm getting this error, which I thought was going to be resolved with the virtio.

![image](https://user-images.githubusercontent.com/19286882/213193998-e83d2708-7e43-4b76-973d-98fcfd483941.png)

![image](https://user-images.githubusercontent.com/19286882/213194279-c7a3b1cf-69cb-4478-a83c-72b9cde189b5.png)

![image](https://user-images.githubusercontent.com/19286882/213194447-9e5efcc4-d702-4967-ae3c-9c45684533e8.png)

**Comment by hyru-ar** [comment]
Hi @tuxtof , that was there, just a little below, sorry. I took the exact same sysprep from the example you told me to.

![image](https://user-images.githubusercontent.com/19286882/213538713-0c07c1f3-d5ae-4e3d-b617-7026032b3c14.png)

**Comment by tuxtof** [comment]
it seems you try to create a windows 2019 image
but you install win 2016 driver not sure it works
there is a 2019 driver
![image](https://user-images.githubusercontent.com/180613/213731869-e18cabc6-ef6e-4f83-9366-5bd0988af2b4.png)

**Comment by hyru-ar** [comment]
I downloaded the one from the support page, which is an ISO, with no specific OS. And on that driver block I placed 2019, but I got the same result.

![image](https://user-images.githubusercontent.com/19286882/213771967-49085d1e-2ce0-4409-bd93-68be28483eb6.png)

**Comment by hyru-ar** [comment]
Hi @tuxtof , good morning! is it possible to schedule a working session with you? It would be greatly appreciated.

Thanks!

**Comment by tuxtof** [comment]
@hyru-ar can you share you entire hcl package file please with all the information to reproduce

**Comment by hyru-ar** [comment]
Hi @tuxtof, gm! Sorry for the late response, but I was not around. PFA the files we are using to test the creation, you will find some extra files, but it was all for testing. Right now the source is like in the examples you mention just to figure out if we were able to at least deploy a template image with no extra things on it.

[pkr_ntx_windows_support_files.zip](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/files/10664721/pkr_ntx_windows_support_files.zip)

Please let me know if you need something else of if you need to jump on a call. Thanks in advance!

**Comment by tuxtof** [comment]
Hi @hyru-ar 

i make quick test on the package you share me using `answer_files/autounattend.xml` and the main issue is that nowhere in the file you ask to install driver from the virtio CD


you need to add a block like

```
        <component name="Microsoft-Windows-PnpCustomizationsWinPE" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS"
            xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <DriverPaths>
                <PathAndCredentials wcm:action="add" wcm:keyValue="1">
                    <Path>e:\Windows Server 2019\x64</Path>
                </PathAndCredentials>
            </DriverPaths>
        </component>
```

inside the ` <settings pass="windowsPE">` part

after that you have a new error about your the partition you defined , it seems he is not happy with `System Reserved` label.


In all case your packer structure is nice and you have only windows `autounattend.xml` issues.

Best in this case is to come back to microsoft to ask them help

++

**Comment by ktinthecloud** [comment]
I was trying to upgrade the version of VirtIO that I was using in my Packer build from 1.1.7 to 1.2.1 and was getting this error also...
![image](https://user-images.githubusercontent.com/63941280/219514673-5866d361-1b98-43d9-82c3-be4d0829124c.png)

After changing the following line in my autounattend.xml file, it is now working:

Changed from:
` <Path>e:\Windows Server 2019\amd64</Path>`

To:
` <Path>e:\Windows Server 2019\x64</Path>`

Thanks @tuxtof

**Comment by tuxtof** [comment]
nice good news, blocked by a simple path :-D
