### ISSUE TITLE
SSH Timeout while creating Linux Image on Nutanix

### ISSUE THREAD

**Issue by vivekdabas** [nutanix-cloud-native/packer-plugin-nutanix#85]
/kind bug

**What steps did you take, and what happened:**

I am trying to create a Linux image on Nutanix using the provided plugin. The VM gets created on Nutanix using the ISO image included in the source and kickstart configuration file. However, the SSH communicator times out after waiting for around 20 minutes. I can establish an SSH connection to the newly created VM through packer, assuming SSH is not the issue.  

**What did you expect to happen:**
I expect the rhel-hardening script that we want to run once the VM is provisioned should be executed on the VM and, at the end, result in creating an image. 

**Anything else you would like to add:**

I am attaching all the snapshots and the code used for provisioning the Linux image.

Screenshot 1: Packer error of SSH timing out.
Screenshot 2: VM console created through Packer on Nutanix.
Screenshot 3: SSH connection to new VM created on Nutanix using Packer
Code we are using is also attached.

_Miscellaneous information that will assist in solving the issue._

**Environment:**

- packer-plugin-nutanix version (use `packer plugins installed`): 

/home/cfgmgr.svc/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.3.1_x5.0_linux_amd64
/home/cfgmgr.svc/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.4.0_x5.0_linux_amd64

- Packer version (use `packer version`): 

1.8.5

- OS (e.g. from `/etc/os-release`): 

NAME="Red Hat Enterprise Linux"
VERSION="8.5 (Ootpa)"

![Linux-Packer1](https://user-images.githubusercontent.com/26025867/212192417-55cec494-554a-4888-928b-a07a96bfb6a4.jpg)
![Linux-Packer2](https://user-images.githubusercontent.com/26025867/212192488-2e84834f-ebbf-4862-b63f-0e185d907cfd.jpg)
![Linux-Packer3](https://user-images.githubusercontent.com/26025867/212192518-ab8504a5-f019-433c-92d8-e42f3c81a2e8.jpg)
[linux-packer.tar.gz](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/files/10406464/linux-packer.tar.gz)

**Comment by tuxtof** [comment]
Hello @vivekdabas based on your linux-packer.tar.gz
your packer try to connect with user root
you ks configure and you test with user admin

when you have this kind of unclear issue please launch 
PACKER_LOG=1 packer build , to have deeper details

**Comment by vivekdabas** [comment]
@tuxtof Issue is resolved for the Linux image. Thanks for your assistance.

**Comment by tuxtof** [comment]
nice
you are welcome
