### ISSUE TITLE
Kickstart iso is not used by Linux VM

### ISSUE THREAD

**Issue by BrGitHub11** [nutanix-cloud-native/packer-plugin-nutanix#91]
/kind bug

**What steps did you take and what happened:**

I configured packer to start a VM on our Nutanix cluster from a Rocky Linux iso.
I provided a kickstart file and configured packer to use it:
  cd_files          = ["ks.cfg"]
  cd_label          = "OEMDRV"
But the VM doesn't recognize the CDROM. It seems that the label is missing even though the log says that the label was created:
2023/02/01 19:56:47 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:56:47 CD label is set to OEMDRV
If I log into the VM and do a lsblk the Rocky cd is shown with a label but the kickstart cd doesn't have a label.

**What did you expect to happen:**

The kickstart iso should have the correct label.

**Anything else you would like to add:**

If I create my own kickstart iso and add it to the config and omit the lines above my config is running as expected.

**Environment:**

- packer-plugin-nutanix version (use `packer plugins installed`): 
packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64
- Packer version (use `packer version`): 
Packer v1.8.4
- OS (e.g. from `/etc/os-release`): 
macOS Version 12.6.2

**Comment by tuxtof** [comment]
Hello @BrGitHub11 

can you give a detailled trace with `PACKER_LOG=1 packer build .` and also share your hcl file please

**Comment by tuxtof** [comment]
please use the `blkid` command to check the label

exemple of what i get from a jsut created packer image
```
blkid
/dev/sr0: BLOCK_SIZE="2048" UUID="2023-02-02-13-01-13-00" LABEL="config-2" TYPE="iso9660"
/dev/sr1: BLOCK_SIZE="2048" UUID="2023-02-02-13-00-37-00" LABEL="OEMDRV" TYPE="iso9660"
/dev/sda2: SEC_TYPE="msdos" UUID="7B77-95E7" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="68b2905b-df3e-4fb3-80fa-49d1e773aa33"
/dev/sda3: LABEL="root" UUID="bb235b3c-0bf6-4374-bf6a-60d9f360d90b" BLOCK_SIZE="512" TYPE="xfs" PARTUUID="6264d520-3fb9-423f-8ab8-7a0a8e3d3562"
/dev/sda1: PARTUUID="fac7f1fb-3e8d-4137-a512-961de09a5549"
```

**Comment by BrGitHub11** [comment]
`2023/02/01 19:56:47 [INFO] Packer version: 1.8.4 [go1.18.5 darwin amd64]
2023/02/01 19:56:47 [TRACE] discovering plugins in /usr/local/bin
2023/02/01 19:56:47 [TRACE] discovering plugins in /Users/username/.config/packer/plugins
2023/02/01 19:56:47 [DEBUG] Discovered plugin: nutanix = /Users/username/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64
2023/02/01 19:56:47 [INFO] found external [-packer-default-plugin-name-] builders from nutanix plugin
2023/02/01 19:56:47 [TRACE] discovering plugins in .
2023/02/01 19:56:47 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2023/02/01 19:56:47 [INFO] PACKER_CONFIG env var set; attempting to open config file: /Users/username/.packerconfig
2023/02/01 19:56:47 [WARN] Config file doesn't exist: /Users/username/.packerconfig
2023/02/01 19:56:47 [INFO] Setting cache directory: /Users/username/.cache/packer
2023/02/01 19:56:47 [TRACE] listing potential installations for "github.com/nutanix-cloud-native/nutanix" that match ">= 0.3.0". plugingetter.ListInstallationsOptions{FromFolders:[]string{"/usr/local/bin/packer", ".", "/Users/username/.config/packer/plugins"}, BinaryInstallationOptions:plugingetter.BinaryInstallationOptions{APIVersionMajor:"5", APIVersionMinor:"0", OS:"darwin", ARCH:"amd64", Ext:"", Checksummers:[]plugingetter.Checksummer{plugingetter.Checksummer{Type:"sha256", Hash:(*sha256.digest)(0xc000994600)}}}}
2023/02/01 19:56:47 [TRACE] Found the following "github.com/nutanix-cloud-native/nutanix" installations: [{/Users/username/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 v0.4.0}]
2023/02/01 19:56:47 [INFO] found external [-packer-default-plugin-name-] builders from nutanix plugin
2023/02/01 19:56:47 [TRACE] validateValue: not active for nutanix_subnet_uuid, so skipping
2023/02/01 19:56:47 [TRACE] validateValue: not active for nutanix_cluster, so skipping
2023/02/01 19:56:47 [TRACE] validateValue: not active for rocky_iso_image_name, so skipping
2023/02/01 19:56:47 [TRACE] validateValue: not active for nutanix_username, so skipping
2023/02/01 19:56:47 [TRACE] validateValue: not active for nutanix_password, so skipping
2023/02/01 19:56:47 [TRACE] validateValue: not active for nutanix_endpoint, so skipping
2023/02/01 19:56:47 [TRACE] validateValue: not active for nutanix_port, so skipping
2023/02/01 19:56:47 [TRACE] validateValue: not active for nutanix_insecure, so skipping
2023/02/01 19:56:47 [TRACE] Starting external plugin /Users/username/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 start builder -packer-default-plugin-name-
2023/02/01 19:56:47 Starting plugin: /Users/username/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 []string{"/Users/username/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64", "start", "builder", "-packer-default-plugin-name-"}
2023/02/01 19:56:47 Waiting for RPC address for: /Users/username/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64
2023/02/01 19:56:47 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:56:47 Plugin address: unix /var/folders/6y/65z7796n4c763gvfdwmjwdm40000gn/T/packer-plugin775841542
2023/02/01 19:56:47 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:56:47 Waiting for connection...
2023/02/01 19:56:47 Received unix RPC address for /Users/username/.config/packer/plugins/github.com/nutanix-cloud-native/nutanix/packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64: addr is /var/folders/6y/65z7796n4c763gvfdwmjwdm40000gn/T/packer-plugin775841542
2023/02/01 19:56:47 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:56:47 Serving a plugin connection...
2023/02/01 19:56:47 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:56:47 [TRACE] starting builder -packer-default-plugin-name-
2023/02/01 19:56:47 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:56:47 No Communicator Type assigned but SSH Creds available, setting to 'SSH'
2023/02/01 19:56:47 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:56:47 No Nutanix Port configured, defaulting to '9440'
2023/02/01 19:56:47 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:56:47 No correct VM Boot Type configured, defaulting to 'legacy'
2023/02/01 19:56:47 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:56:47 No vmname assigned, setting to Packer-6HNMXSOR
2023/02/01 19:56:47 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:56:47 SSHPort not set, defaulting to 22
2023/02/01 19:56:47 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:56:47 SSHTimeout not set, defaulting to 20min
2023/02/01 19:56:47 [TRACE] Starting internal plugin packer-provisioner-shell
2023/02/01 19:56:47 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-provisioner-shell"}
2023/02/01 19:56:47 Waiting for RPC address for: /usr/local/bin/packer
2023/02/01 19:56:47 packer-provisioner-shell plugin: [INFO] Packer version: 1.8.4 [go1.18.5 darwin amd64]
2023/02/01 19:56:47 packer-provisioner-shell plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2023/02/01 19:56:47 packer-provisioner-shell plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /Users/username/.packerconfig
2023/02/01 19:56:47 packer-provisioner-shell plugin: [WARN] Config file doesn't exist: /Users/username/.packerconfig
2023/02/01 19:56:47 packer-provisioner-shell plugin: [INFO] Setting cache directory: /Users/username/.cache/packer
2023/02/01 19:56:47 packer-provisioner-shell plugin: args: []string{"packer-provisioner-shell"}
2023/02/01 19:56:47 packer-provisioner-shell plugin: Plugin address: unix /var/folders/6y/65z7796n4c763gvfdwmjwdm40000gn/T/packer-plugin2321314652
2023/02/01 19:56:47 packer-provisioner-shell plugin: Waiting for connection...
2023/02/01 19:56:47 Received unix RPC address for /usr/local/bin/packer: addr is /var/folders/6y/65z7796n4c763gvfdwmjwdm40000gn/T/packer-plugin2321314652
2023/02/01 19:56:47 packer-provisioner-shell plugin: Serving a plugin connection...
2023/02/01 19:56:47 Build debug mode: false
2023/02/01 19:56:47 Force build: false
2023/02/01 19:56:47 On error: 
2023/02/01 19:56:47 Waiting on builds to complete...
2023/02/01 19:56:47 Starting build run: nutanix.rocky
2023/02/01 19:56:47 Running builder: 
2023/02/01 19:56:47 [INFO] (telemetry) Starting builder nutanix.rocky
nutanix.rocky: output will be in this color.

2023/02/01 19:56:47 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:56:47 PC Host from config: myserver
2023/02/01 19:56:47 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:56:47 CD label is set to OEMDRV
==> nutanix.rocky: Creating CD disk...
2023/02/01 19:56:47 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:56:47 CD path: /var/folders/6y/65z7796n4c763gvfdwmjwdm40000gn/T/packer2321466242.iso
2023/02/01 19:56:47 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:56:47 Wrote 1581 bytes to ks.cfg
2023/02/01 19:56:47 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:56:47 Executing: /usr/bin/hdiutil [makehybrid -o /var/folders/6y/65z7796n4c763gvfdwmjwdm40000gn/T/packer2321466242.iso -hfs -joliet -iso -default-volume-name OEMDRV /var/folders/6y/65z7796n4c763gvfdwmjwdm40000gn/T/packer_to_cdrom4259578361]
    nutanix.rocky: Creating hybrid image...
    nutanix.rocky: Done copying paths from CD_dirs
==> nutanix.rocky: Creating Packer Builder VM on Nutanix Cluster.
2023/02/01 19:56:47 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:56:47 Check for temporary iso-disks to attach
2023/02/01 19:56:47 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:56:47 temporary iso found, /var/folders/6y/65z7796n4c763gvfdwmjwdm40000gn/T/packer2321466242.iso
2023/02/01 19:57:15 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:57:15 Creating Image: RUNNING
2023/02/01 19:57:28 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:57:28 Creating Image: COMPLETE
==> nutanix.rocky: Temporary ISO uploaded
2023/02/01 19:59:21 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:59:21 waiting for vm (79db77aa-b9b3-410b-8bfb-5c26be93a227) to create: 2b58b6a9-9ffd-4a1b-a4be-cb4cd51865fd
2023/02/01 19:59:31 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:59:31 Current status is: RUNNING
2023/02/01 19:59:43 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:59:43 Current status is: RUNNING
2023/02/01 19:59:58 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 19:59:58 Current status is: RUNNING
2023/02/01 20:00:15 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 20:00:15 vm created successfully: COMPLETE
2023/02/01 20:00:15 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 20:00:15 [INFO] Waiting for IP, up to timeout: 15m0s
2023/02/01 20:00:24 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 20:00:24 Waiting VM (79db77aa-b9b3-410b-8bfb-5c26be93a227) ip configuration
2023/02/01 20:00:37 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 20:00:37 Waiting VM (79db77aa-b9b3-410b-8bfb-5c26be93a227) ip configuration
2023/02/01 20:00:51 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 20:00:51 Waiting VM (79db77aa-b9b3-410b-8bfb-5c26be93a227) ip configuration
2023/02/01 20:01:05 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 20:01:05 Waiting VM (79db77aa-b9b3-410b-8bfb-5c26be93a227) ip configuration
2023/02/01 20:01:17 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 20:01:17 Waiting VM (79db77aa-b9b3-410b-8bfb-5c26be93a227) ip configuration
2023/02/01 20:01:30 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 20:01:30 Waiting VM (79db77aa-b9b3-410b-8bfb-5c26be93a227) ip configuration
2023/02/01 20:01:42 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 20:01:42 Waiting VM (79db77aa-b9b3-410b-8bfb-5c26be93a227) ip configuration
2023/02/01 20:01:56 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 20:01:56 Waiting VM (79db77aa-b9b3-410b-8bfb-5c26be93a227) ip configuration
2023/02/01 20:02:09 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 20:02:09 Waiting VM (79db77aa-b9b3-410b-8bfb-5c26be93a227) ip configuration
2023/02/01 20:02:21 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 20:02:21 Waiting VM (79db77aa-b9b3-410b-8bfb-5c26be93a227) ip configuration
2023/02/01 20:02:34 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 20:02:34 Waiting VM (79db77aa-b9b3-410b-8bfb-5c26be93a227) ip configuration
2023/02/01 20:02:47 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 20:02:47 Waiting VM (79db77aa-b9b3-410b-8bfb-5c26be93a227) ip configuration
2023/02/01 20:03:01 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 20:03:01 Waiting VM (79db77aa-b9b3-410b-8bfb-5c26be93a227) ip configuration
2023/02/01 20:03:15 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 20:03:15 Waiting VM (79db77aa-b9b3-410b-8bfb-5c26be93a227) ip configuration
2023/02/01 20:03:29 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 20:03:29 Waiting VM (79db77aa-b9b3-410b-8bfb-5c26be93a227) ip configuration
2023/02/01 20:03:41 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 20:03:41 Waiting VM (79db77aa-b9b3-410b-8bfb-5c26be93a227) ip configuration
2023/02/01 20:03:54 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 20:03:54 Waiting VM (79db77aa-b9b3-410b-8bfb-5c26be93a227) ip configuration
2023/02/01 20:04:06 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 20:04:06 Waiting VM (79db77aa-b9b3-410b-8bfb-5c26be93a227) ip configuration
2023/02/01 20:04:21 packer-plugin-nutanix_v0.4.0_x5.0_darwin_amd64 plugin: 2023/02/01 20:04:21 Waiting VM (79db77aa-b9b3-410b-8bfb-5c26be93a227) ip configuration`

**Comment by BrGitHub11** [comment]
`source "nutanix" "rocky" {
  nutanix_username = var.nutanix_username
  nutanix_password = var.nutanix_password
  nutanix_endpoint = var.nutanix_endpoint
  nutanix_insecure = var.nutanix_insecure
  cluster_name     = var.nutanix_cluster
  os_type          = "Linux"
  
  vm_disks {
      image_type = "ISO_IMAGE"
      source_image_name = var.rocky_iso_image_name
  }

  vm_disks {
      image_type = "DISK"
      disk_size_gb = 64
  }

  vm_nics {
    subnet_uuid     = var.nutanix_subnet_uuid
  }

  cd_files          = ["ks.cfg"]
  cd_label          = "OEMDRV"
  
  image_name        = "rocky-{{isotime `02-Jan-06_3:04PM`}}"
  force_deregister  = true

  shutdown_command  = "echo 'packer' | sudo -S shutdown -P now"
  shutdown_timeout  = "2m"
  ssh_password      = "secret"
  ssh_username      = "root"

  cpu               = 2
  memory_mb         = "8192"
}

`

**Comment by BrGitHub11** [comment]
Ok. Tried the blkid command and it shows the label. But lsblk doesn't. Don't know why.
But more important: the OS doesn't use the kickstart CD.
If I create a kickstart CD myself it's working.

**Comment by tuxtof** [comment]
Hello @BrGitHub11 

i found your issue

for info the ISO is not created by the nutanix plugin but directly by packer binary by using an external program assuming that you have a command line tool installed that can handle the iso creation. Packer will use one of the following tools:

xorriso
mkisofs
hdiutil (normally found in macOS)
oscdimg (normally found in Windows as part of the Windows ADK)

on your mac in the log you can see packer is using hdiutil.

it seems there is a bug in the way hdiutil create the iso image who break the autoload logic

on my side i use xorriso `brew install xorriso` who perfectly fix the issue

i create a packer issue here
https://github.com/hashicorp/packer/issues/12241

**Comment by BrGitHub11** [comment]
Hi, thanks! It's working now.
