### ISSUE TITLE
Add support for defining image category

### ISSUE THREAD

**Issue by thewelshvader** [nutanix-cloud-native/packer-plugin-nutanix#97]
/kind feature

Ability to define a Prism category key and value for the images in the Packer config. This would enable image placement policies to take effect after the build finishes. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- packer-plugin-nutanix version (use `packer plugins installed`):  packer-plugin-nutanix_v0.3.1_x5.0_linux_amd64
- Packer version : 1.8.5
- OS (e.g. from `/etc/os-release`): RHEL 8.5

**Comment by tuxtof** [comment]
Hi @thewelshvader i merge a commit with the change in master

can you check if it is ok for you

new parameters are

- `image_category_key` (string) - Name of the category to assign to the image.
- `image_category_value` (string) - Value of the category to assign to the image.

**Comment by thewelshvader** [comment]
Hi @tuxtof 

Sure I will test it.

Correct me if I'm wrong - I need to build the plugin from the main branch?
And I'm not familiar with Go - do I need to run _make build_ from the same environment I am running Packer in? (RHEL8.5 in my case)

Thanks

**Comment by tuxtof** [comment]
Yes a `make dev` inside the repo make the job

but if. no urgent i will make a new release soon if you prefer

**Comment by thewelshvader** [comment]
Ok thanks, happy to wait for the next release!

**Comment by tuxtof** [comment]
Hello @thewelshvader v0.5.0 was released please give a try
